package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.Empresa;
import pe.bhintranet.model.dao.EmpresaDAO;

public class EmpresaDAOImpl extends SqlMapClientDaoSupport implements EmpresaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public EmpresaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int deleteByPrimaryKey(Long codempresa) {
        Empresa key = new Empresa();
        key.setCodempresa(codempresa);
        int rows = getSqlMapClientTemplate().delete("empresa.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insert(Empresa record) {
        getSqlMapClientTemplate().insert("empresa.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insertSelective(Empresa record) {
        getSqlMapClientTemplate().insert("empresa.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Empresa selectByPrimaryKey(Long codempresa) {
        Empresa key = new Empresa();
        key.setCodempresa(codempresa);
        Empresa record = (Empresa) getSqlMapClientTemplate().queryForObject("empresa.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKeySelective(Empresa record) {
        int rows = getSqlMapClientTemplate().update("empresa.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKey(Empresa record) {
        int rows = getSqlMapClientTemplate().update("empresa.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}