package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.Franquicia;
import pe.bhintranet.model.dao.FranquiciaDAO;

public class FranquiciaDAOImpl extends SqlMapClientDaoSupport implements FranquiciaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table franquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public FranquiciaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table franquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int deleteByPrimaryKey(Integer codfranquicia) {
        Franquicia key = new Franquicia();
        key.setCodfranquicia(codfranquicia);
        int rows = getSqlMapClientTemplate().delete("franquicia.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table franquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insert(Franquicia record) {
        getSqlMapClientTemplate().insert("franquicia.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table franquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insertSelective(Franquicia record) {
        getSqlMapClientTemplate().insert("franquicia.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table franquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Franquicia selectByPrimaryKey(Integer codfranquicia) {
        Franquicia key = new Franquicia();
        key.setCodfranquicia(codfranquicia);
        Franquicia record = (Franquicia) getSqlMapClientTemplate().queryForObject("franquicia.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table franquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKeySelective(Franquicia record) {
        int rows = getSqlMapClientTemplate().update("franquicia.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table franquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKey(Franquicia record) {
        int rows = getSqlMapClientTemplate().update("franquicia.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}