package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.Modulo;
import pe.bhintranet.model.dao.ModuloDAO;

public class ModuloDAOImpl extends SqlMapClientDaoSupport implements ModuloDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table modulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public ModuloDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table modulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int deleteByPrimaryKey(Integer codmodulo) {
        Modulo key = new Modulo();
        key.setCodmodulo(codmodulo);
        int rows = getSqlMapClientTemplate().delete("modulo.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table modulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insert(Modulo record) {
        getSqlMapClientTemplate().insert("modulo.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table modulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insertSelective(Modulo record) {
        getSqlMapClientTemplate().insert("modulo.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table modulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Modulo selectByPrimaryKey(Integer codmodulo) {
        Modulo key = new Modulo();
        key.setCodmodulo(codmodulo);
        Modulo record = (Modulo) getSqlMapClientTemplate().queryForObject("modulo.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table modulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKeySelective(Modulo record) {
        int rows = getSqlMapClientTemplate().update("modulo.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table modulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKey(Modulo record) {
        int rows = getSqlMapClientTemplate().update("modulo.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}