package pe.bhintranet.model.dao.ibatis;

import java.util.Collection;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.Parametro;
import pe.bhintranet.model.bean.Usuario;
import pe.bhintranet.model.dao.ParametroDAO;

public class ParametroDAOImpl extends SqlMapClientDaoSupport implements ParametroDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public ParametroDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int deleteByPrimaryKey(String codargumento, Integer codparametro, String grupo) {
        Parametro key = new Parametro();
        key.setCodargumento(codargumento);
        key.setCodparametro(codparametro);
        key.setGrupo(grupo);
        int rows = getSqlMapClientTemplate().delete("parametro.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insert(Parametro record) {
        getSqlMapClientTemplate().insert("parametro.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insertSelective(Parametro record) {
        getSqlMapClientTemplate().insert("parametro.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Parametro selectByPrimaryKey(String codargumento, Integer codparametro, String grupo) {
        Parametro key = new Parametro();
        key.setCodargumento(codargumento);
        key.setCodparametro(codparametro);
        key.setGrupo(grupo);
        Parametro record = (Parametro) getSqlMapClientTemplate().queryForObject("parametro.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKeySelective(Parametro record) {
        int rows = getSqlMapClientTemplate().update("parametro.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKey(Parametro record) {
        int rows = getSqlMapClientTemplate().update("parametro.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @Override
    public Collection listarPorCodParametro(Parametro record) {

            return  getSqlMapClientTemplate().queryForList("parametro.ibatorgenerated_selectByCodParametro", record);
    }
}