package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.Perfil;
import pe.bhintranet.model.dao.PerfilDAO;

public class PerfilDAOImpl extends SqlMapClientDaoSupport implements PerfilDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public PerfilDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int deleteByPrimaryKey(Integer codperfil) {
        Perfil key = new Perfil();
        key.setCodperfil(codperfil);
        int rows = getSqlMapClientTemplate().delete("perfil.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insert(Perfil record) {
        getSqlMapClientTemplate().insert("perfil.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insertSelective(Perfil record) {
        getSqlMapClientTemplate().insert("perfil.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Perfil selectByPrimaryKey(Integer codperfil) {
        Perfil key = new Perfil();
        key.setCodperfil(codperfil);
        Perfil record = (Perfil) getSqlMapClientTemplate().queryForObject("perfil.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKeySelective(Perfil record) {
        int rows = getSqlMapClientTemplate().update("perfil.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKey(Perfil record) {
        int rows = getSqlMapClientTemplate().update("perfil.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}