package pe.bhintranet.model.dao.ibatis;

import java.util.List;
import java.util.Collection;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.Propiedad;
import pe.bhintranet.model.bean.Usuario;
import pe.bhintranet.model.dao.PropiedadDAO;

public class PropiedadDAOImpl extends SqlMapClientDaoSupport implements PropiedadDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table propiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public PropiedadDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table propiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public int deleteByPrimaryKey(Long codpropiedad) {
        Propiedad key = new Propiedad();
        key.setCodpropiedad(codpropiedad);
        int rows = getSqlMapClientTemplate().delete("propiedad.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table propiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void insert(Propiedad record) {
        getSqlMapClientTemplate().insert("propiedad.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table propiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void insertSelective(Propiedad record) {
        getSqlMapClientTemplate().insert("propiedad.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table propiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Propiedad selectByPrimaryKey(Long codpropiedad) {
        Propiedad key = new Propiedad();
        key.setCodpropiedad(codpropiedad);
        Propiedad record = (Propiedad) getSqlMapClientTemplate().queryForObject("propiedad.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table propiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public int updateByPrimaryKeySelective(Propiedad record) {
        int rows = getSqlMapClientTemplate().update("propiedad.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table propiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public int updateByPrimaryKey(Propiedad record) {
        int rows = getSqlMapClientTemplate().update("propiedad.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    //personalizado
    @Override
    public Collection listarPorFiltro(Propiedad record) {

            return  getSqlMapClientTemplate().queryForList("propiedad.ibatorgenerated_selectByFiltro", record);
    }   
     public List listarPorFiltroRC(Propiedad record) {

            return  getSqlMapClientTemplate().queryForList("propiedad.ibatorgenerated_selectByFiltro", record);
    } 
    //  
}