package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.Provincia;
import pe.bhintranet.model.dao.ProvinciaDAO;

public class ProvinciaDAOImpl extends SqlMapClientDaoSupport implements ProvinciaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public ProvinciaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int deleteByPrimaryKey(Integer codprovincia) {
        Provincia key = new Provincia();
        key.setCodprovincia(codprovincia);
        int rows = getSqlMapClientTemplate().delete("provincia.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insert(Provincia record) {
        getSqlMapClientTemplate().insert("provincia.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insertSelective(Provincia record) {
        getSqlMapClientTemplate().insert("provincia.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Provincia selectByPrimaryKey(Integer codprovincia) {
        Provincia key = new Provincia();
        key.setCodprovincia(codprovincia);
        Provincia record = (Provincia) getSqlMapClientTemplate().queryForObject("provincia.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKeySelective(Provincia record) {
        int rows = getSqlMapClientTemplate().update("provincia.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKey(Provincia record) {
        int rows = getSqlMapClientTemplate().update("provincia.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}