package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.TasacionArchivo;
import pe.bhintranet.model.dao.TasacionArchivoDAO;

public class TasacionArchivoDAOImpl extends SqlMapClientDaoSupport implements TasacionArchivoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public TasacionArchivoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int deleteByPrimaryKey(Long codtasacionarchivo) {
        TasacionArchivo key = new TasacionArchivo();
        key.setCodtasacionarchivo(codtasacionarchivo);
        int rows = getSqlMapClientTemplate().delete("tasacionarchivo.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insert(TasacionArchivo record) {
        getSqlMapClientTemplate().insert("tasacionarchivo.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insertSelective(TasacionArchivo record) {
        getSqlMapClientTemplate().insert("tasacionarchivo.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public TasacionArchivo selectByPrimaryKey(Long codtasacionarchivo) {
        TasacionArchivo key = new TasacionArchivo();
        key.setCodtasacionarchivo(codtasacionarchivo);
        TasacionArchivo record = (TasacionArchivo) getSqlMapClientTemplate().queryForObject("tasacionarchivo.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKeySelective(TasacionArchivo record) {
        int rows = getSqlMapClientTemplate().update("tasacionarchivo.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKey(TasacionArchivo record) {
        int rows = getSqlMapClientTemplate().update("tasacionarchivo.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}