package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.TasacionEdificacion;
import pe.bhintranet.model.dao.TasacionEdificacionDAO;

public class TasacionEdificacionDAOImpl extends SqlMapClientDaoSupport implements TasacionEdificacionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public TasacionEdificacionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int deleteByPrimaryKey(Long codtasacion, Integer nroitem) {
        TasacionEdificacion key = new TasacionEdificacion();
        key.setCodtasacion(codtasacion);
        key.setNroitem(nroitem);
        int rows = getSqlMapClientTemplate().delete("tasacionedificacion.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insert(TasacionEdificacion record) {
        getSqlMapClientTemplate().insert("tasacionedificacion.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insertSelective(TasacionEdificacion record) {
        getSqlMapClientTemplate().insert("tasacionedificacion.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public TasacionEdificacion selectByPrimaryKey(Long codtasacion, Integer nroitem) {
        TasacionEdificacion key = new TasacionEdificacion();
        key.setCodtasacion(codtasacion);
        key.setNroitem(nroitem);
        TasacionEdificacion record = (TasacionEdificacion) getSqlMapClientTemplate().queryForObject("tasacionedificacion.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKeySelective(TasacionEdificacion record) {
        int rows = getSqlMapClientTemplate().update("tasacionedificacion.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKey(TasacionEdificacion record) {
        int rows = getSqlMapClientTemplate().update("tasacionedificacion.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}