package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.Tasacion;
import pe.bhintranet.model.dao.TasacionDAO;

public class TasacionDAOImpl extends SqlMapClientDaoSupport implements TasacionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public TasacionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int deleteByPrimaryKey(Long codtasacion) {
        Tasacion key = new Tasacion();
        key.setCodtasacion(codtasacion);
        int rows = getSqlMapClientTemplate().delete("tasacion.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insert(Tasacion record) {
        getSqlMapClientTemplate().insert("tasacion.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insertSelective(Tasacion record) {
        getSqlMapClientTemplate().insert("tasacion.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Tasacion selectByPrimaryKey(Long codtasacion) {
        Tasacion key = new Tasacion();
        key.setCodtasacion(codtasacion);
        Tasacion record = (Tasacion) getSqlMapClientTemplate().queryForObject("tasacion.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKeySelective(Tasacion record) {
        int rows = getSqlMapClientTemplate().update("tasacion.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKey(Tasacion record) {
        int rows = getSqlMapClientTemplate().update("tasacion.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}