package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.TasacionLinderos;
import pe.bhintranet.model.dao.TasacionLinderosDAO;

public class TasacionLinderosDAOImpl extends SqlMapClientDaoSupport implements TasacionLinderosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public TasacionLinderosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int deleteByPrimaryKey(Long codtasacion, Integer nroitem) {
        TasacionLinderos key = new TasacionLinderos();
        key.setCodtasacion(codtasacion);
        key.setNroitem(nroitem);
        int rows = getSqlMapClientTemplate().delete("tasacionlinderos.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insert(TasacionLinderos record) {
        getSqlMapClientTemplate().insert("tasacionlinderos.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insertSelective(TasacionLinderos record) {
        getSqlMapClientTemplate().insert("tasacionlinderos.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public TasacionLinderos selectByPrimaryKey(Long codtasacion, Integer nroitem) {
        TasacionLinderos key = new TasacionLinderos();
        key.setCodtasacion(codtasacion);
        key.setNroitem(nroitem);
        TasacionLinderos record = (TasacionLinderos) getSqlMapClientTemplate().queryForObject("tasacionlinderos.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKeySelective(TasacionLinderos record) {
        int rows = getSqlMapClientTemplate().update("tasacionlinderos.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKey(TasacionLinderos record) {
        int rows = getSqlMapClientTemplate().update("tasacionlinderos.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}