package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.TasacionDistribucion;
import pe.bhintranet.model.dao.TasacionDistribucionDAO;

public class TasacionDistribucionDAOImpl extends SqlMapClientDaoSupport implements TasacionDistribucionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasaciondistribucion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public TasacionDistribucionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasaciondistribucion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int deleteByPrimaryKey(Long codtasacion, Integer nroitem) {
        TasacionDistribucion key = new TasacionDistribucion();
        key.setCodtasacion(codtasacion);
        key.setNroitem(nroitem);
        int rows = getSqlMapClientTemplate().delete("tasaciondistribucion.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasaciondistribucion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insert(TasacionDistribucion record) {
        getSqlMapClientTemplate().insert("tasaciondistribucion.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasaciondistribucion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void insertSelective(TasacionDistribucion record) {
        getSqlMapClientTemplate().insert("tasaciondistribucion.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasaciondistribucion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public TasacionDistribucion selectByPrimaryKey(Long codtasacion, Integer nroitem) {
        TasacionDistribucion key = new TasacionDistribucion();
        key.setCodtasacion(codtasacion);
        key.setNroitem(nroitem);
        TasacionDistribucion record = (TasacionDistribucion) getSqlMapClientTemplate().queryForObject("tasaciondistribucion.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasaciondistribucion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKeySelective(TasacionDistribucion record) {
        int rows = getSqlMapClientTemplate().update("tasaciondistribucion.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasaciondistribucion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public int updateByPrimaryKey(TasacionDistribucion record) {
        int rows = getSqlMapClientTemplate().update("tasaciondistribucion.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}