package pe.bhintranet.model.dao.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.UsuarioPerfil;
import pe.bhintranet.model.dao.UsuarioPerfilDAO;

public class UsuarioPerfilDAOImpl extends SqlMapClientDaoSupport implements UsuarioPerfilDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public UsuarioPerfilDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int deleteByPrimaryKey(Integer codmoduloperfil, Long codusuario) {
        UsuarioPerfil key = new UsuarioPerfil();
        key.setCodmoduloperfil(codmoduloperfil);
        key.setCodusuario(codusuario);
        int rows = getSqlMapClientTemplate().delete("usuarioperfil.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insert(UsuarioPerfil record) {
        getSqlMapClientTemplate().insert("usuarioperfil.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void insertSelective(UsuarioPerfil record) {
        getSqlMapClientTemplate().insert("usuarioperfil.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public UsuarioPerfil selectByPrimaryKey(Integer codmoduloperfil, Long codusuario) {
        UsuarioPerfil key = new UsuarioPerfil();
        key.setCodmoduloperfil(codmoduloperfil);
        key.setCodusuario(codusuario);
        UsuarioPerfil record = (UsuarioPerfil) getSqlMapClientTemplate().queryForObject("usuarioperfil.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKeySelective(UsuarioPerfil record) {
        int rows = getSqlMapClientTemplate().update("usuarioperfil.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public int updateByPrimaryKey(UsuarioPerfil record) {
        int rows = getSqlMapClientTemplate().update("usuarioperfil.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}