package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.Departamento;

public interface DepartamentoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table departamento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int deleteByPrimaryKey(Integer coddepartamento);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table departamento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insert(Departamento record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table departamento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insertSelective(Departamento record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table departamento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    Departamento selectByPrimaryKey(Integer coddepartamento);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table departamento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKeySelective(Departamento record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table departamento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKey(Departamento record);
}