package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.Empresa;

public interface EmpresaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int deleteByPrimaryKey(Long codempresa);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insert(Empresa record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insertSelective(Empresa record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    Empresa selectByPrimaryKey(Long codempresa);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKeySelective(Empresa record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table empresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKey(Empresa record);
}