package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.Pais;

public interface PaisDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int deleteByPrimaryKey(Integer codpais);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insert(Pais record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insertSelective(Pais record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    Pais selectByPrimaryKey(Integer codpais);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKeySelective(Pais record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKey(Pais record);
}