package pe.bhintranet.model.dao;

import java.util.Collection;
import pe.bhintranet.model.bean.Parametro;

public interface ParametroDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int deleteByPrimaryKey(String codargumento, Integer codparametro, String grupo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insert(Parametro record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insertSelective(Parametro record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    Parametro selectByPrimaryKey(String codargumento, Integer codparametro, String grupo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKeySelective(Parametro record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKey(Parametro record);
    //personalizado
    public Collection listarPorCodParametro(Parametro record);
}