package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.Perfil;

public interface PerfilDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int deleteByPrimaryKey(Integer codperfil);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insert(Perfil record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insertSelective(Perfil record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    Perfil selectByPrimaryKey(Integer codperfil);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKeySelective(Perfil record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table perfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKey(Perfil record);
}