package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.Provincia;

public interface ProvinciaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int deleteByPrimaryKey(Integer codprovincia);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insert(Provincia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insertSelective(Provincia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    Provincia selectByPrimaryKey(Integer codprovincia);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKeySelective(Provincia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table provincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKey(Provincia record);
}