package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.TasacionArchivo;

public interface TasacionArchivoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int deleteByPrimaryKey(Long codtasacionarchivo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insert(TasacionArchivo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insertSelective(TasacionArchivo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    TasacionArchivo selectByPrimaryKey(Long codtasacionarchivo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKeySelective(TasacionArchivo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionarchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKey(TasacionArchivo record);
}