package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.Tasacion;

public interface TasacionDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int deleteByPrimaryKey(Long codtasacion);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insert(Tasacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insertSelective(Tasacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    Tasacion selectByPrimaryKey(Long codtasacion);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKeySelective(Tasacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKey(Tasacion record);
}