package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.TasacionLinderos;

public interface TasacionLinderosDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int deleteByPrimaryKey(Long codtasacion, Integer nroitem);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insert(TasacionLinderos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insertSelective(TasacionLinderos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    TasacionLinderos selectByPrimaryKey(Long codtasacion, Integer nroitem);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKeySelective(TasacionLinderos record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionlinderos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKey(TasacionLinderos record);
}