package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.TasacionEdificacion;

public interface TasacionEdificacionDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int deleteByPrimaryKey(Long codtasacion, Integer nroitem);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insert(TasacionEdificacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    void insertSelective(TasacionEdificacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    TasacionEdificacion selectByPrimaryKey(Long codtasacion, Integer nroitem);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKeySelective(TasacionEdificacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tasacionedificacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    int updateByPrimaryKey(TasacionEdificacion record);
}