package pe.bhintranet.model.dao;

import pe.bhintranet.model.bean.UsuarioPerfil;

public interface UsuarioPerfilDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int deleteByPrimaryKey(Integer codmoduloperfil, Long codusuario);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insert(UsuarioPerfil record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    void insertSelective(UsuarioPerfil record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    UsuarioPerfil selectByPrimaryKey(Integer codmoduloperfil, Long codusuario);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKeySelective(UsuarioPerfil record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuarioperfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    int updateByPrimaryKey(UsuarioPerfil record);
}