package pe.bhintranet.model.bean;

import java.util.Date;

public class Cliente {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.codCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codcliente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.nombres
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String nombres;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.apellidos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String apellidos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.dni
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String dni;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.ruc
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String ruc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.correo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String correo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.telefono
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String telefono;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.celular
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String celular;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.sexo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String sexo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.direccion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String direccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechaalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechabaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cliente.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.codCliente
     *
     * @return the value of cliente.codCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodcliente() {
        return codcliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.codCliente
     *
     * @param codcliente the value for cliente.codCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodcliente(Long codcliente) {
        this.codcliente = codcliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.nombres
     *
     * @return the value of cliente.nombres
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.nombres
     *
     * @param nombres the value for cliente.nombres
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setNombres(String nombres) {
        this.nombres = nombres == null ? null : nombres.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.apellidos
     *
     * @return the value of cliente.apellidos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getApellidos() {
        return apellidos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.apellidos
     *
     * @param apellidos the value for cliente.apellidos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos == null ? null : apellidos.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.dni
     *
     * @return the value of cliente.dni
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDni() {
        return dni;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.dni
     *
     * @param dni the value for cliente.dni
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDni(String dni) {
        this.dni = dni == null ? null : dni.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.ruc
     *
     * @return the value of cliente.ruc
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getRuc() {
        return ruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.ruc
     *
     * @param ruc the value for cliente.ruc
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setRuc(String ruc) {
        this.ruc = ruc == null ? null : ruc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.correo
     *
     * @return the value of cliente.correo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.correo
     *
     * @param correo the value for cliente.correo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCorreo(String correo) {
        this.correo = correo == null ? null : correo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.telefono
     *
     * @return the value of cliente.telefono
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.telefono
     *
     * @param telefono the value for cliente.telefono
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono == null ? null : telefono.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.celular
     *
     * @return the value of cliente.celular
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getCelular() {
        return celular;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.celular
     *
     * @param celular the value for cliente.celular
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCelular(String celular) {
        this.celular = celular == null ? null : celular.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.sexo
     *
     * @return the value of cliente.sexo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getSexo() {
        return sexo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.sexo
     *
     * @param sexo the value for cliente.sexo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setSexo(String sexo) {
        this.sexo = sexo == null ? null : sexo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.direccion
     *
     * @return the value of cliente.direccion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.direccion
     *
     * @param direccion the value for cliente.direccion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion == null ? null : direccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.fechaRegistro
     *
     * @return the value of cliente.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.fechaRegistro
     *
     * @param fecharegistro the value for cliente.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.fechaAlta
     *
     * @return the value of cliente.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechaalta() {
        return fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.fechaAlta
     *
     * @param fechaalta the value for cliente.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.fechaBaja
     *
     * @return the value of cliente.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.fechaBaja
     *
     * @param fechabaja the value for cliente.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cliente.estado
     *
     * @return the value of cliente.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cliente.estado
     *
     * @param estado the value for cliente.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }
}