package pe.bhintranet.model.bean;

import java.util.Date;

public class Departamento {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column departamento.codDepartamento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer coddepartamento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column departamento.codPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codpais;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column departamento.nombreCorto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrecorto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column departamento.nombreLargo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrelargo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column departamento.nroPostal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nropostal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column departamento.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column departamento.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column departamento.codDepartamento
     *
     * @return the value of departamento.codDepartamento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCoddepartamento() {
        return coddepartamento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column departamento.codDepartamento
     *
     * @param coddepartamento the value for departamento.codDepartamento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCoddepartamento(Integer coddepartamento) {
        this.coddepartamento = coddepartamento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column departamento.codPais
     *
     * @return the value of departamento.codPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodpais() {
        return codpais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column departamento.codPais
     *
     * @param codpais the value for departamento.codPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodpais(Integer codpais) {
        this.codpais = codpais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column departamento.nombreCorto
     *
     * @return the value of departamento.nombreCorto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrecorto() {
        return nombrecorto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column departamento.nombreCorto
     *
     * @param nombrecorto the value for departamento.nombreCorto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrecorto(String nombrecorto) {
        this.nombrecorto = nombrecorto == null ? null : nombrecorto.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column departamento.nombreLargo
     *
     * @return the value of departamento.nombreLargo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrelargo() {
        return nombrelargo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column departamento.nombreLargo
     *
     * @param nombrelargo the value for departamento.nombreLargo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrelargo(String nombrelargo) {
        this.nombrelargo = nombrelargo == null ? null : nombrelargo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column departamento.nroPostal
     *
     * @return the value of departamento.nroPostal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNropostal() {
        return nropostal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column departamento.nroPostal
     *
     * @param nropostal the value for departamento.nroPostal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNropostal(String nropostal) {
        this.nropostal = nropostal == null ? null : nropostal.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column departamento.fechaRegistro
     *
     * @return the value of departamento.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column departamento.fechaRegistro
     *
     * @param fecharegistro the value for departamento.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column departamento.estado
     *
     * @return the value of departamento.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column departamento.estado
     *
     * @param estado the value for departamento.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }
}