package pe.bhintranet.model.bean;

import java.util.Date;

public class Distrito {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column distrito.codDistrito
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer coddistrito;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column distrito.codProvincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codprovincia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column distrito.nombreCorto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrecorto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column distrito.nombreLargo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrelargo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column distrito.nroPostal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nropostal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column distrito.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column distrito.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    public Distrito() {        
    }    
    public Distrito(Integer codprovincia) {
        this.codprovincia = codprovincia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column distrito.codDistrito
     *
     * @return the value of distrito.codDistrito
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCoddistrito() {
        return coddistrito;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column distrito.codDistrito
     *
     * @param coddistrito the value for distrito.codDistrito
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCoddistrito(Integer coddistrito) {
        this.coddistrito = coddistrito;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column distrito.codProvincia
     *
     * @return the value of distrito.codProvincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodprovincia() {
        return codprovincia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column distrito.codProvincia
     *
     * @param codprovincia the value for distrito.codProvincia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodprovincia(Integer codprovincia) {
        this.codprovincia = codprovincia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column distrito.nombreCorto
     *
     * @return the value of distrito.nombreCorto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrecorto() {
        return nombrecorto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column distrito.nombreCorto
     *
     * @param nombrecorto the value for distrito.nombreCorto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrecorto(String nombrecorto) {
        this.nombrecorto = nombrecorto == null ? null : nombrecorto.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column distrito.nombreLargo
     *
     * @return the value of distrito.nombreLargo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrelargo() {
        return nombrelargo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column distrito.nombreLargo
     *
     * @param nombrelargo the value for distrito.nombreLargo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrelargo(String nombrelargo) {
        this.nombrelargo = nombrelargo == null ? null : nombrelargo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column distrito.nroPostal
     *
     * @return the value of distrito.nroPostal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNropostal() {
        return nropostal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column distrito.nroPostal
     *
     * @param nropostal the value for distrito.nroPostal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNropostal(String nropostal) {
        this.nropostal = nropostal == null ? null : nropostal.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column distrito.fechaRegistro
     *
     * @return the value of distrito.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column distrito.fechaRegistro
     *
     * @param fecharegistro the value for distrito.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column distrito.estado
     *
     * @return the value of distrito.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column distrito.estado
     *
     * @param estado the value for distrito.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }
}