package pe.bhintranet.model.bean;

import java.util.Date;

public class Empresa {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.codEmpresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codempresa;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.ruc
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String ruc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.rasonSocial
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String rasonsocial;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.razonComercial
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String razoncomercial;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.activo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String activo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.telefono
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String telefono;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.celular
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String celular;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.representante
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String representante;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.direccion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String direccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.obsBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String obsbaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechaalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechabaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column empresa.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.codEmpresa
     *
     * @return the value of empresa.codEmpresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodempresa() {
        return codempresa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.codEmpresa
     *
     * @param codempresa the value for empresa.codEmpresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodempresa(Long codempresa) {
        this.codempresa = codempresa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.ruc
     *
     * @return the value of empresa.ruc
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getRuc() {
        return ruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.ruc
     *
     * @param ruc the value for empresa.ruc
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setRuc(String ruc) {
        this.ruc = ruc == null ? null : ruc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.rasonSocial
     *
     * @return the value of empresa.rasonSocial
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getRasonsocial() {
        return rasonsocial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.rasonSocial
     *
     * @param rasonsocial the value for empresa.rasonSocial
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setRasonsocial(String rasonsocial) {
        this.rasonsocial = rasonsocial == null ? null : rasonsocial.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.razonComercial
     *
     * @return the value of empresa.razonComercial
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getRazoncomercial() {
        return razoncomercial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.razonComercial
     *
     * @param razoncomercial the value for empresa.razonComercial
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setRazoncomercial(String razoncomercial) {
        this.razoncomercial = razoncomercial == null ? null : razoncomercial.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.activo
     *
     * @return the value of empresa.activo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getActivo() {
        return activo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.activo
     *
     * @param activo the value for empresa.activo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setActivo(String activo) {
        this.activo = activo == null ? null : activo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.telefono
     *
     * @return the value of empresa.telefono
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.telefono
     *
     * @param telefono the value for empresa.telefono
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono == null ? null : telefono.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.celular
     *
     * @return the value of empresa.celular
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getCelular() {
        return celular;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.celular
     *
     * @param celular the value for empresa.celular
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCelular(String celular) {
        this.celular = celular == null ? null : celular.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.representante
     *
     * @return the value of empresa.representante
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getRepresentante() {
        return representante;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.representante
     *
     * @param representante the value for empresa.representante
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setRepresentante(String representante) {
        this.representante = representante == null ? null : representante.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.direccion
     *
     * @return the value of empresa.direccion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.direccion
     *
     * @param direccion the value for empresa.direccion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion == null ? null : direccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.obsBaja
     *
     * @return the value of empresa.obsBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getObsbaja() {
        return obsbaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.obsBaja
     *
     * @param obsbaja the value for empresa.obsBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setObsbaja(String obsbaja) {
        this.obsbaja = obsbaja == null ? null : obsbaja.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.fechaRegistro
     *
     * @return the value of empresa.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.fechaRegistro
     *
     * @param fecharegistro the value for empresa.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.fechaAlta
     *
     * @return the value of empresa.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechaalta() {
        return fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.fechaAlta
     *
     * @param fechaalta the value for empresa.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.fechaBaja
     *
     * @return the value of empresa.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.fechaBaja
     *
     * @param fechabaja the value for empresa.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column empresa.estado
     *
     * @return the value of empresa.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column empresa.estado
     *
     * @param estado the value for empresa.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }
}