package pe.bhintranet.model.bean;

import java.util.Date;

public class Franquicia {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codfranquicia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.ruc
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String ruc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.razonSocial
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String razonsocial;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.razonComercial
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String razoncomercial;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.telefono
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String telefono;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.representanteLegal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String representantelegal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.celular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String celular;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.paginaWeb
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String paginaweb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechaalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechabaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column franquicia.nombreArchivoLogo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrearchivologo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.codFranquicia
     *
     * @return the value of franquicia.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodfranquicia() {
        return codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.codFranquicia
     *
     * @param codfranquicia the value for franquicia.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodfranquicia(Integer codfranquicia) {
        this.codfranquicia = codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.ruc
     *
     * @return the value of franquicia.ruc
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getRuc() {
        return ruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.ruc
     *
     * @param ruc the value for franquicia.ruc
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setRuc(String ruc) {
        this.ruc = ruc == null ? null : ruc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.razonSocial
     *
     * @return the value of franquicia.razonSocial
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getRazonsocial() {
        return razonsocial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.razonSocial
     *
     * @param razonsocial the value for franquicia.razonSocial
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial == null ? null : razonsocial.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.razonComercial
     *
     * @return the value of franquicia.razonComercial
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getRazoncomercial() {
        return razoncomercial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.razonComercial
     *
     * @param razoncomercial the value for franquicia.razonComercial
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setRazoncomercial(String razoncomercial) {
        this.razoncomercial = razoncomercial == null ? null : razoncomercial.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.telefono
     *
     * @return the value of franquicia.telefono
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.telefono
     *
     * @param telefono the value for franquicia.telefono
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono == null ? null : telefono.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.representanteLegal
     *
     * @return the value of franquicia.representanteLegal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getRepresentantelegal() {
        return representantelegal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.representanteLegal
     *
     * @param representantelegal the value for franquicia.representanteLegal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setRepresentantelegal(String representantelegal) {
        this.representantelegal = representantelegal == null ? null : representantelegal.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.celular
     *
     * @return the value of franquicia.celular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCelular() {
        return celular;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.celular
     *
     * @param celular the value for franquicia.celular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCelular(String celular) {
        this.celular = celular == null ? null : celular.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.paginaWeb
     *
     * @return the value of franquicia.paginaWeb
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getPaginaweb() {
        return paginaweb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.paginaWeb
     *
     * @param paginaweb the value for franquicia.paginaWeb
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setPaginaweb(String paginaweb) {
        this.paginaweb = paginaweb == null ? null : paginaweb.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.fechaRegistro
     *
     * @return the value of franquicia.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.fechaRegistro
     *
     * @param fecharegistro the value for franquicia.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.fechaAlta
     *
     * @return the value of franquicia.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechaalta() {
        return fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.fechaAlta
     *
     * @param fechaalta the value for franquicia.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.fechaBaja
     *
     * @return the value of franquicia.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.fechaBaja
     *
     * @param fechabaja the value for franquicia.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.estado
     *
     * @return the value of franquicia.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.estado
     *
     * @param estado the value for franquicia.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.usuarioCrea
     *
     * @return the value of franquicia.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.usuarioCrea
     *
     * @param usuariocrea the value for franquicia.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.usuarioModifica
     *
     * @return the value of franquicia.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.usuarioModifica
     *
     * @param usuariomodifica the value for franquicia.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.fechaCrea
     *
     * @return the value of franquicia.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.fechaCrea
     *
     * @param fechacrea the value for franquicia.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.fechaModifica
     *
     * @return the value of franquicia.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.fechaModifica
     *
     * @param fechamodifica the value for franquicia.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column franquicia.nombreArchivoLogo
     *
     * @return the value of franquicia.nombreArchivoLogo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrearchivologo() {
        return nombrearchivologo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column franquicia.nombreArchivoLogo
     *
     * @param nombrearchivologo the value for franquicia.nombreArchivoLogo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrearchivologo(String nombrearchivologo) {
        this.nombrearchivologo = nombrearchivologo == null ? null : nombrearchivologo.trim();
    }
}