package pe.bhintranet.model.bean;

import java.util.Date;

public class Pais {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pais.codPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codpais;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pais.nombreCortoPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrecortopais;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pais.nombreLargoPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrelargopais;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pais.nroPostal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nropostal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pais.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pais.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pais.codPais
     *
     * @return the value of pais.codPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodpais() {
        return codpais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pais.codPais
     *
     * @param codpais the value for pais.codPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodpais(Integer codpais) {
        this.codpais = codpais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pais.nombreCortoPais
     *
     * @return the value of pais.nombreCortoPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrecortopais() {
        return nombrecortopais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pais.nombreCortoPais
     *
     * @param nombrecortopais the value for pais.nombreCortoPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrecortopais(String nombrecortopais) {
        this.nombrecortopais = nombrecortopais == null ? null : nombrecortopais.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pais.nombreLargoPais
     *
     * @return the value of pais.nombreLargoPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrelargopais() {
        return nombrelargopais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pais.nombreLargoPais
     *
     * @param nombrelargopais the value for pais.nombreLargoPais
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrelargopais(String nombrelargopais) {
        this.nombrelargopais = nombrelargopais == null ? null : nombrelargopais.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pais.nroPostal
     *
     * @return the value of pais.nroPostal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNropostal() {
        return nropostal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pais.nroPostal
     *
     * @param nropostal the value for pais.nroPostal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNropostal(String nropostal) {
        this.nropostal = nropostal == null ? null : nropostal.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pais.fechaRegistro
     *
     * @return the value of pais.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pais.fechaRegistro
     *
     * @param fecharegistro the value for pais.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pais.estado
     *
     * @return the value of pais.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pais.estado
     *
     * @param estado the value for pais.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }
}