package pe.bhintranet.model.bean;

import java.util.Date;

public class Parametro {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.codArgumento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String codargumento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.codParametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codparametro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.grupo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String grupo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.nombreCorto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrecorto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.nombreLargo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrelargo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.nombreAbreviado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombreabreviado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parametro.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechamodifica;

    public Parametro() {
        
    }
    public Parametro(Integer codparametro) {
        this.codparametro = codparametro;
    }
    


    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.codArgumento
     *
     * @return the value of parametro.codArgumento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCodargumento() {
        return codargumento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.codArgumento
     *
     * @param codargumento the value for parametro.codArgumento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodargumento(String codargumento) {
        this.codargumento = codargumento == null ? null : codargumento.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.codParametro
     *
     * @return the value of parametro.codParametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodparametro() {
        return codparametro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.codParametro
     *
     * @param codparametro the value for parametro.codParametro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodparametro(Integer codparametro) {
        this.codparametro = codparametro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.grupo
     *
     * @return the value of parametro.grupo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getGrupo() {
        return grupo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.grupo
     *
     * @param grupo the value for parametro.grupo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setGrupo(String grupo) {
        this.grupo = grupo == null ? null : grupo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.nombreCorto
     *
     * @return the value of parametro.nombreCorto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrecorto() {
        return nombrecorto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.nombreCorto
     *
     * @param nombrecorto the value for parametro.nombreCorto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrecorto(String nombrecorto) {
        this.nombrecorto = nombrecorto == null ? null : nombrecorto.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.nombreLargo
     *
     * @return the value of parametro.nombreLargo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrelargo() {
        return nombrelargo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.nombreLargo
     *
     * @param nombrelargo the value for parametro.nombreLargo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrelargo(String nombrelargo) {
        this.nombrelargo = nombrelargo == null ? null : nombrelargo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.nombreAbreviado
     *
     * @return the value of parametro.nombreAbreviado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombreabreviado() {
        return nombreabreviado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.nombreAbreviado
     *
     * @param nombreabreviado the value for parametro.nombreAbreviado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombreabreviado(String nombreabreviado) {
        this.nombreabreviado = nombreabreviado == null ? null : nombreabreviado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.fechaRegistro
     *
     * @return the value of parametro.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.fechaRegistro
     *
     * @param fecharegistro the value for parametro.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.estado
     *
     * @return the value of parametro.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.estado
     *
     * @param estado the value for parametro.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.usuarioCrea
     *
     * @return the value of parametro.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.usuarioCrea
     *
     * @param usuariocrea the value for parametro.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.usuarioModifica
     *
     * @return the value of parametro.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.usuarioModifica
     *
     * @param usuariomodifica the value for parametro.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.fechaCrea
     *
     * @return the value of parametro.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.fechaCrea
     *
     * @param fechacrea the value for parametro.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parametro.fechaModifica
     *
     * @return the value of parametro.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parametro.fechaModifica
     *
     * @param fechamodifica the value for parametro.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }
}