package pe.bhintranet.model.bean;

public class Perfil {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column perfil.codPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codperfil;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column perfil.codModulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codmodulo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column perfil.nombreCortoPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrecortoperfil;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column perfil.nombreLargoPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrelargoperfil;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column perfil.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column perfil.codPerfil
     *
     * @return the value of perfil.codPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodperfil() {
        return codperfil;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column perfil.codPerfil
     *
     * @param codperfil the value for perfil.codPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodperfil(Integer codperfil) {
        this.codperfil = codperfil;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column perfil.codModulo
     *
     * @return the value of perfil.codModulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodmodulo() {
        return codmodulo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column perfil.codModulo
     *
     * @param codmodulo the value for perfil.codModulo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodmodulo(Integer codmodulo) {
        this.codmodulo = codmodulo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column perfil.nombreCortoPerfil
     *
     * @return the value of perfil.nombreCortoPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrecortoperfil() {
        return nombrecortoperfil;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column perfil.nombreCortoPerfil
     *
     * @param nombrecortoperfil the value for perfil.nombreCortoPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrecortoperfil(String nombrecortoperfil) {
        this.nombrecortoperfil = nombrecortoperfil == null ? null : nombrecortoperfil.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column perfil.nombreLargoPerfil
     *
     * @return the value of perfil.nombreLargoPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrelargoperfil() {
        return nombrelargoperfil;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column perfil.nombreLargoPerfil
     *
     * @param nombrelargoperfil the value for perfil.nombreLargoPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrelargoperfil(String nombrelargoperfil) {
        this.nombrelargoperfil = nombrelargoperfil == null ? null : nombrelargoperfil.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column perfil.estado
     *
     * @return the value of perfil.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column perfil.estado
     *
     * @param estado the value for perfil.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }
}