package pe.bhintranet.model.bean;

import java.util.Date;

public class Persona {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.codPersona
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Long codpersona;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.dni
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String dni;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.nombres
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombres;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.apellidos
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String apellidos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.sexo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String sexo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.fechaNacimiento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechanacimiento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.telefono
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String telefono;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.celular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String celular;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.correoEmpresa
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String correoempresa;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.correoPersonal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String correopersonal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.direccion
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String direccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column persona.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codfranquicia;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.codPersona
     *
     * @return the value of persona.codPersona
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Long getCodpersona() {
        return codpersona;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.codPersona
     *
     * @param codpersona the value for persona.codPersona
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodpersona(Long codpersona) {
        this.codpersona = codpersona;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.dni
     *
     * @return the value of persona.dni
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getDni() {
        return dni;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.dni
     *
     * @param dni the value for persona.dni
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setDni(String dni) {
        this.dni = dni == null ? null : dni.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.nombres
     *
     * @return the value of persona.nombres
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.nombres
     *
     * @param nombres the value for persona.nombres
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombres(String nombres) {
        this.nombres = nombres == null ? null : nombres.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.apellidos
     *
     * @return the value of persona.apellidos
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getApellidos() {
        return apellidos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.apellidos
     *
     * @param apellidos the value for persona.apellidos
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos == null ? null : apellidos.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.sexo
     *
     * @return the value of persona.sexo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getSexo() {
        return sexo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.sexo
     *
     * @param sexo the value for persona.sexo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setSexo(String sexo) {
        this.sexo = sexo == null ? null : sexo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.fechaNacimiento
     *
     * @return the value of persona.fechaNacimiento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechanacimiento() {
        return fechanacimiento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.fechaNacimiento
     *
     * @param fechanacimiento the value for persona.fechaNacimiento
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.telefono
     *
     * @return the value of persona.telefono
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.telefono
     *
     * @param telefono the value for persona.telefono
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono == null ? null : telefono.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.celular
     *
     * @return the value of persona.celular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCelular() {
        return celular;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.celular
     *
     * @param celular the value for persona.celular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCelular(String celular) {
        this.celular = celular == null ? null : celular.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.correoEmpresa
     *
     * @return the value of persona.correoEmpresa
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCorreoempresa() {
        return correoempresa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.correoEmpresa
     *
     * @param correoempresa the value for persona.correoEmpresa
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCorreoempresa(String correoempresa) {
        this.correoempresa = correoempresa == null ? null : correoempresa.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.correoPersonal
     *
     * @return the value of persona.correoPersonal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCorreopersonal() {
        return correopersonal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.correoPersonal
     *
     * @param correopersonal the value for persona.correoPersonal
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCorreopersonal(String correopersonal) {
        this.correopersonal = correopersonal == null ? null : correopersonal.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.direccion
     *
     * @return the value of persona.direccion
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.direccion
     *
     * @param direccion the value for persona.direccion
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion == null ? null : direccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.estado
     *
     * @return the value of persona.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.estado
     *
     * @param estado the value for persona.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.usuarioCrea
     *
     * @return the value of persona.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.usuarioCrea
     *
     * @param usuariocrea the value for persona.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.usuarioModifica
     *
     * @return the value of persona.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.usuarioModifica
     *
     * @param usuariomodifica the value for persona.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.fechaCrea
     *
     * @return the value of persona.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.fechaCrea
     *
     * @param fechacrea the value for persona.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.fechaModifica
     *
     * @return the value of persona.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.fechaModifica
     *
     * @param fechamodifica the value for persona.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column persona.codFranquicia
     *
     * @return the value of persona.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodfranquicia() {
        return codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column persona.codFranquicia
     *
     * @param codfranquicia the value for persona.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodfranquicia(Integer codfranquicia) {
        this.codfranquicia = codfranquicia;
    }
}