package pe.bhintranet.model.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Propiedad {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codPropiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Long codpropiedad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.notaEspanol
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String notaespanol;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.descripcionEspanol
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String descripcionespanol;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.notaIngles
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String notaingles;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.descripcionIngles
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String descripcioningles;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codPersonaAsesor
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Long codpersonaasesor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codSituacionEstado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String codsituacionestado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.comisionPorcentaje
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private BigDecimal comisionporcentaje;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.fechaTerminoContrato
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Date fechaterminocontrato;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.exclusiva
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String exclusiva;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codPais
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer codpais;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codDepartamento
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer coddepartamento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codProvincia
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer codprovincia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codDistrito
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer coddistrito;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codTipoDireccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String codtipodireccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.direccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String direccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.nroDireccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String nrodireccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codTipoPropiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String codtipopropiedad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codTipoOferta
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String codtipooferta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.areaTerrenoUm
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String areaterrenoum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.areaTerrenoCantidad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private BigDecimal areaterrenocantidad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.areaContruccionUm
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String areacontruccionum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.areaConstruccionCantidad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private BigDecimal areaconstruccioncantidad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.precioMoneda
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String preciomoneda;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.precioValor
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private BigDecimal preciovalor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.cantidadhabitaciones
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer cantidadhabitaciones;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.cantidadBano
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer cantidadbano;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indConLicencia
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indconlicencia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indPuertaCerrada
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indpuertacerrada;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.tipoZonificacion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String tipozonificacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.PisosPermitidos
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer pisospermitidos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.linderosM2
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private BigDecimal linderosm2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.cantidadPisos
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer cantidadpisos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.anioContruccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer aniocontruccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.aniosAntiguedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer aniosantiguedad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indEstacionamiento
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indestacionamiento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indFrenteMar
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indfrentemar;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indEstreno
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indestreno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indRemodelado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indremodelado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.fechaProEntregaProyecto
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Date fechaproentregaproyecto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indFullAmoblado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indfullamoblado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indSemiAmoblado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indsemiamoblado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indSoloLineaBlanca
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indsololineablanca;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indFrenteParque
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indfrenteparque;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indPiscina
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indpiscina;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indGimnasio
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indgimnasio;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indBBQ
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indbbq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indJardin
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indjardin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indPentHouse
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indpenthouse;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indDuplex
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indduplex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indTriplex
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indtriplex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indPisosPorcelanato
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indpisosporcelanato;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.indPisosLaminados
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String indpisoslaminados;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Date fechaalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Date fechabaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.fechaUltimoEvento
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Date fechaultimoevento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Integer codfranquicia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedad.codUsuarioAsesor
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    private Long codusuarioasesor;

    //personalizado
    private String usuarioasesor;
    private String nombretipopropiedad;
    private String nombredistrito;

    public String getUsuarioasesor() {
        return usuarioasesor;
    }

    public void setUsuarioasesor(String usuarioasesor) {
        this.usuarioasesor = usuarioasesor;
    }

    public String getNombretipopropiedad() {
        return nombretipopropiedad;
    }

    public void setNombretipopropiedad(String nombretipopropiedad) {
        this.nombretipopropiedad = nombretipopropiedad;
    }

    public String getNombredistrito() {
        return nombredistrito;
    }

    public void setNombredistrito(String nombredistrito) {
        this.nombredistrito = nombredistrito;
    }
    
    //fin personalizado
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codPropiedad
     *
     * @return the value of propiedad.codPropiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Long getCodpropiedad() {
        return codpropiedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codPropiedad
     *
     * @param codpropiedad the value for propiedad.codPropiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodpropiedad(Long codpropiedad) {
        this.codpropiedad = codpropiedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.notaEspanol
     *
     * @return the value of propiedad.notaEspanol
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getNotaespanol() {
        return notaespanol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.notaEspanol
     *
     * @param notaespanol the value for propiedad.notaEspanol
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setNotaespanol(String notaespanol) {
        this.notaespanol = notaespanol == null ? null : notaespanol.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.descripcionEspanol
     *
     * @return the value of propiedad.descripcionEspanol
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getDescripcionespanol() {
        return descripcionespanol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.descripcionEspanol
     *
     * @param descripcionespanol the value for propiedad.descripcionEspanol
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setDescripcionespanol(String descripcionespanol) {
        this.descripcionespanol = descripcionespanol == null ? null : descripcionespanol.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.notaIngles
     *
     * @return the value of propiedad.notaIngles
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getNotaingles() {
        return notaingles;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.notaIngles
     *
     * @param notaingles the value for propiedad.notaIngles
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setNotaingles(String notaingles) {
        this.notaingles = notaingles == null ? null : notaingles.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.descripcionIngles
     *
     * @return the value of propiedad.descripcionIngles
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getDescripcioningles() {
        return descripcioningles;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.descripcionIngles
     *
     * @param descripcioningles the value for propiedad.descripcionIngles
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setDescripcioningles(String descripcioningles) {
        this.descripcioningles = descripcioningles == null ? null : descripcioningles.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codPersonaAsesor
     *
     * @return the value of propiedad.codPersonaAsesor
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Long getCodpersonaasesor() {
        return codpersonaasesor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codPersonaAsesor
     *
     * @param codpersonaasesor the value for propiedad.codPersonaAsesor
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodpersonaasesor(Long codpersonaasesor) {
        this.codpersonaasesor = codpersonaasesor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codSituacionEstado
     *
     * @return the value of propiedad.codSituacionEstado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getCodsituacionestado() {
        return codsituacionestado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codSituacionEstado
     *
     * @param codsituacionestado the value for propiedad.codSituacionEstado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodsituacionestado(String codsituacionestado) {
        this.codsituacionestado = codsituacionestado == null ? null : codsituacionestado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.comisionPorcentaje
     *
     * @return the value of propiedad.comisionPorcentaje
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public BigDecimal getComisionporcentaje() {
        return comisionporcentaje;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.comisionPorcentaje
     *
     * @param comisionporcentaje the value for propiedad.comisionPorcentaje
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setComisionporcentaje(BigDecimal comisionporcentaje) {
        this.comisionporcentaje = comisionporcentaje;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.fechaTerminoContrato
     *
     * @return the value of propiedad.fechaTerminoContrato
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Date getFechaterminocontrato() {
        return fechaterminocontrato;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.fechaTerminoContrato
     *
     * @param fechaterminocontrato the value for propiedad.fechaTerminoContrato
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setFechaterminocontrato(Date fechaterminocontrato) {
        this.fechaterminocontrato = fechaterminocontrato;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.exclusiva
     *
     * @return the value of propiedad.exclusiva
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getExclusiva() {
        return exclusiva;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.exclusiva
     *
     * @param exclusiva the value for propiedad.exclusiva
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setExclusiva(String exclusiva) {
        this.exclusiva = exclusiva == null ? null : exclusiva.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codPais
     *
     * @return the value of propiedad.codPais
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getCodpais() {
        return codpais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codPais
     *
     * @param codpais the value for propiedad.codPais
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodpais(Integer codpais) {
        this.codpais = codpais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codDepartamento
     *
     * @return the value of propiedad.codDepartamento
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getCoddepartamento() {
        return coddepartamento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codDepartamento
     *
     * @param coddepartamento the value for propiedad.codDepartamento
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCoddepartamento(Integer coddepartamento) {
        this.coddepartamento = coddepartamento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codProvincia
     *
     * @return the value of propiedad.codProvincia
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getCodprovincia() {
        return codprovincia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codProvincia
     *
     * @param codprovincia the value for propiedad.codProvincia
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodprovincia(Integer codprovincia) {
        this.codprovincia = codprovincia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codDistrito
     *
     * @return the value of propiedad.codDistrito
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getCoddistrito() {
        return coddistrito;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codDistrito
     *
     * @param coddistrito the value for propiedad.codDistrito
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCoddistrito(Integer coddistrito) {
        this.coddistrito = coddistrito;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codTipoDireccion
     *
     * @return the value of propiedad.codTipoDireccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getCodtipodireccion() {
        return codtipodireccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codTipoDireccion
     *
     * @param codtipodireccion the value for propiedad.codTipoDireccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodtipodireccion(String codtipodireccion) {
        this.codtipodireccion = codtipodireccion == null ? null : codtipodireccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.direccion
     *
     * @return the value of propiedad.direccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.direccion
     *
     * @param direccion the value for propiedad.direccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion == null ? null : direccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.nroDireccion
     *
     * @return the value of propiedad.nroDireccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getNrodireccion() {
        return nrodireccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.nroDireccion
     *
     * @param nrodireccion the value for propiedad.nroDireccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setNrodireccion(String nrodireccion) {
        this.nrodireccion = nrodireccion == null ? null : nrodireccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codTipoPropiedad
     *
     * @return the value of propiedad.codTipoPropiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getCodtipopropiedad() {
        return codtipopropiedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codTipoPropiedad
     *
     * @param codtipopropiedad the value for propiedad.codTipoPropiedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodtipopropiedad(String codtipopropiedad) {
        this.codtipopropiedad = codtipopropiedad == null ? null : codtipopropiedad.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codTipoOferta
     *
     * @return the value of propiedad.codTipoOferta
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getCodtipooferta() {
        return codtipooferta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codTipoOferta
     *
     * @param codtipooferta the value for propiedad.codTipoOferta
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodtipooferta(String codtipooferta) {
        this.codtipooferta = codtipooferta == null ? null : codtipooferta.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.areaTerrenoUm
     *
     * @return the value of propiedad.areaTerrenoUm
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getAreaterrenoum() {
        return areaterrenoum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.areaTerrenoUm
     *
     * @param areaterrenoum the value for propiedad.areaTerrenoUm
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setAreaterrenoum(String areaterrenoum) {
        this.areaterrenoum = areaterrenoum == null ? null : areaterrenoum.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.areaTerrenoCantidad
     *
     * @return the value of propiedad.areaTerrenoCantidad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public BigDecimal getAreaterrenocantidad() {
        return areaterrenocantidad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.areaTerrenoCantidad
     *
     * @param areaterrenocantidad the value for propiedad.areaTerrenoCantidad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setAreaterrenocantidad(BigDecimal areaterrenocantidad) {
        this.areaterrenocantidad = areaterrenocantidad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.areaContruccionUm
     *
     * @return the value of propiedad.areaContruccionUm
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getAreacontruccionum() {
        return areacontruccionum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.areaContruccionUm
     *
     * @param areacontruccionum the value for propiedad.areaContruccionUm
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setAreacontruccionum(String areacontruccionum) {
        this.areacontruccionum = areacontruccionum == null ? null : areacontruccionum.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.areaConstruccionCantidad
     *
     * @return the value of propiedad.areaConstruccionCantidad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public BigDecimal getAreaconstruccioncantidad() {
        return areaconstruccioncantidad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.areaConstruccionCantidad
     *
     * @param areaconstruccioncantidad the value for propiedad.areaConstruccionCantidad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setAreaconstruccioncantidad(BigDecimal areaconstruccioncantidad) {
        this.areaconstruccioncantidad = areaconstruccioncantidad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.precioMoneda
     *
     * @return the value of propiedad.precioMoneda
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getPreciomoneda() {
        return preciomoneda;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.precioMoneda
     *
     * @param preciomoneda the value for propiedad.precioMoneda
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setPreciomoneda(String preciomoneda) {
        this.preciomoneda = preciomoneda == null ? null : preciomoneda.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.precioValor
     *
     * @return the value of propiedad.precioValor
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public BigDecimal getPreciovalor() {
        return preciovalor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.precioValor
     *
     * @param preciovalor the value for propiedad.precioValor
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setPreciovalor(BigDecimal preciovalor) {
        this.preciovalor = preciovalor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.cantidadhabitaciones
     *
     * @return the value of propiedad.cantidadhabitaciones
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getCantidadhabitaciones() {
        return cantidadhabitaciones;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.cantidadhabitaciones
     *
     * @param cantidadhabitaciones the value for propiedad.cantidadhabitaciones
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCantidadhabitaciones(Integer cantidadhabitaciones) {
        this.cantidadhabitaciones = cantidadhabitaciones;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.cantidadBano
     *
     * @return the value of propiedad.cantidadBano
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getCantidadbano() {
        return cantidadbano;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.cantidadBano
     *
     * @param cantidadbano the value for propiedad.cantidadBano
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCantidadbano(Integer cantidadbano) {
        this.cantidadbano = cantidadbano;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indConLicencia
     *
     * @return the value of propiedad.indConLicencia
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndconlicencia() {
        return indconlicencia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indConLicencia
     *
     * @param indconlicencia the value for propiedad.indConLicencia
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndconlicencia(String indconlicencia) {
        this.indconlicencia = indconlicencia == null ? null : indconlicencia.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indPuertaCerrada
     *
     * @return the value of propiedad.indPuertaCerrada
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndpuertacerrada() {
        return indpuertacerrada;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indPuertaCerrada
     *
     * @param indpuertacerrada the value for propiedad.indPuertaCerrada
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndpuertacerrada(String indpuertacerrada) {
        this.indpuertacerrada = indpuertacerrada == null ? null : indpuertacerrada.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.tipoZonificacion
     *
     * @return the value of propiedad.tipoZonificacion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getTipozonificacion() {
        return tipozonificacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.tipoZonificacion
     *
     * @param tipozonificacion the value for propiedad.tipoZonificacion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setTipozonificacion(String tipozonificacion) {
        this.tipozonificacion = tipozonificacion == null ? null : tipozonificacion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.PisosPermitidos
     *
     * @return the value of propiedad.PisosPermitidos
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getPisospermitidos() {
        return pisospermitidos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.PisosPermitidos
     *
     * @param pisospermitidos the value for propiedad.PisosPermitidos
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setPisospermitidos(Integer pisospermitidos) {
        this.pisospermitidos = pisospermitidos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.linderosM2
     *
     * @return the value of propiedad.linderosM2
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public BigDecimal getLinderosm2() {
        return linderosm2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.linderosM2
     *
     * @param linderosm2 the value for propiedad.linderosM2
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setLinderosm2(BigDecimal linderosm2) {
        this.linderosm2 = linderosm2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.cantidadPisos
     *
     * @return the value of propiedad.cantidadPisos
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getCantidadpisos() {
        return cantidadpisos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.cantidadPisos
     *
     * @param cantidadpisos the value for propiedad.cantidadPisos
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCantidadpisos(Integer cantidadpisos) {
        this.cantidadpisos = cantidadpisos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.anioContruccion
     *
     * @return the value of propiedad.anioContruccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getAniocontruccion() {
        return aniocontruccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.anioContruccion
     *
     * @param aniocontruccion the value for propiedad.anioContruccion
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setAniocontruccion(Integer aniocontruccion) {
        this.aniocontruccion = aniocontruccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.aniosAntiguedad
     *
     * @return the value of propiedad.aniosAntiguedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getAniosantiguedad() {
        return aniosantiguedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.aniosAntiguedad
     *
     * @param aniosantiguedad the value for propiedad.aniosAntiguedad
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setAniosantiguedad(Integer aniosantiguedad) {
        this.aniosantiguedad = aniosantiguedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indEstacionamiento
     *
     * @return the value of propiedad.indEstacionamiento
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndestacionamiento() {
        return indestacionamiento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indEstacionamiento
     *
     * @param indestacionamiento the value for propiedad.indEstacionamiento
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndestacionamiento(String indestacionamiento) {
        this.indestacionamiento = indestacionamiento == null ? null : indestacionamiento.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indFrenteMar
     *
     * @return the value of propiedad.indFrenteMar
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndfrentemar() {
        return indfrentemar;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indFrenteMar
     *
     * @param indfrentemar the value for propiedad.indFrenteMar
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndfrentemar(String indfrentemar) {
        this.indfrentemar = indfrentemar == null ? null : indfrentemar.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indEstreno
     *
     * @return the value of propiedad.indEstreno
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndestreno() {
        return indestreno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indEstreno
     *
     * @param indestreno the value for propiedad.indEstreno
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndestreno(String indestreno) {
        this.indestreno = indestreno == null ? null : indestreno.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indRemodelado
     *
     * @return the value of propiedad.indRemodelado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndremodelado() {
        return indremodelado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indRemodelado
     *
     * @param indremodelado the value for propiedad.indRemodelado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndremodelado(String indremodelado) {
        this.indremodelado = indremodelado == null ? null : indremodelado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.fechaProEntregaProyecto
     *
     * @return the value of propiedad.fechaProEntregaProyecto
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Date getFechaproentregaproyecto() {
        return fechaproentregaproyecto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.fechaProEntregaProyecto
     *
     * @param fechaproentregaproyecto the value for propiedad.fechaProEntregaProyecto
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setFechaproentregaproyecto(Date fechaproentregaproyecto) {
        this.fechaproentregaproyecto = fechaproentregaproyecto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indFullAmoblado
     *
     * @return the value of propiedad.indFullAmoblado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndfullamoblado() {
        return indfullamoblado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indFullAmoblado
     *
     * @param indfullamoblado the value for propiedad.indFullAmoblado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndfullamoblado(String indfullamoblado) {
        this.indfullamoblado = indfullamoblado == null ? null : indfullamoblado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indSemiAmoblado
     *
     * @return the value of propiedad.indSemiAmoblado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndsemiamoblado() {
        return indsemiamoblado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indSemiAmoblado
     *
     * @param indsemiamoblado the value for propiedad.indSemiAmoblado
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndsemiamoblado(String indsemiamoblado) {
        this.indsemiamoblado = indsemiamoblado == null ? null : indsemiamoblado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indSoloLineaBlanca
     *
     * @return the value of propiedad.indSoloLineaBlanca
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndsololineablanca() {
        return indsololineablanca;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indSoloLineaBlanca
     *
     * @param indsololineablanca the value for propiedad.indSoloLineaBlanca
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndsololineablanca(String indsololineablanca) {
        this.indsololineablanca = indsololineablanca == null ? null : indsololineablanca.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indFrenteParque
     *
     * @return the value of propiedad.indFrenteParque
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndfrenteparque() {
        return indfrenteparque;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indFrenteParque
     *
     * @param indfrenteparque the value for propiedad.indFrenteParque
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndfrenteparque(String indfrenteparque) {
        this.indfrenteparque = indfrenteparque == null ? null : indfrenteparque.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indPiscina
     *
     * @return the value of propiedad.indPiscina
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndpiscina() {
        return indpiscina;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indPiscina
     *
     * @param indpiscina the value for propiedad.indPiscina
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndpiscina(String indpiscina) {
        this.indpiscina = indpiscina == null ? null : indpiscina.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indGimnasio
     *
     * @return the value of propiedad.indGimnasio
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndgimnasio() {
        return indgimnasio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indGimnasio
     *
     * @param indgimnasio the value for propiedad.indGimnasio
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndgimnasio(String indgimnasio) {
        this.indgimnasio = indgimnasio == null ? null : indgimnasio.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indBBQ
     *
     * @return the value of propiedad.indBBQ
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndbbq() {
        return indbbq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indBBQ
     *
     * @param indbbq the value for propiedad.indBBQ
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndbbq(String indbbq) {
        this.indbbq = indbbq == null ? null : indbbq.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indJardin
     *
     * @return the value of propiedad.indJardin
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndjardin() {
        return indjardin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indJardin
     *
     * @param indjardin the value for propiedad.indJardin
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndjardin(String indjardin) {
        this.indjardin = indjardin == null ? null : indjardin.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indPentHouse
     *
     * @return the value of propiedad.indPentHouse
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndpenthouse() {
        return indpenthouse;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indPentHouse
     *
     * @param indpenthouse the value for propiedad.indPentHouse
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndpenthouse(String indpenthouse) {
        this.indpenthouse = indpenthouse == null ? null : indpenthouse.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indDuplex
     *
     * @return the value of propiedad.indDuplex
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndduplex() {
        return indduplex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indDuplex
     *
     * @param indduplex the value for propiedad.indDuplex
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndduplex(String indduplex) {
        this.indduplex = indduplex == null ? null : indduplex.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indTriplex
     *
     * @return the value of propiedad.indTriplex
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndtriplex() {
        return indtriplex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indTriplex
     *
     * @param indtriplex the value for propiedad.indTriplex
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndtriplex(String indtriplex) {
        this.indtriplex = indtriplex == null ? null : indtriplex.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indPisosPorcelanato
     *
     * @return the value of propiedad.indPisosPorcelanato
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndpisosporcelanato() {
        return indpisosporcelanato;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indPisosPorcelanato
     *
     * @param indpisosporcelanato the value for propiedad.indPisosPorcelanato
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndpisosporcelanato(String indpisosporcelanato) {
        this.indpisosporcelanato = indpisosporcelanato == null ? null : indpisosporcelanato.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.indPisosLaminados
     *
     * @return the value of propiedad.indPisosLaminados
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getIndpisoslaminados() {
        return indpisoslaminados;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.indPisosLaminados
     *
     * @param indpisoslaminados the value for propiedad.indPisosLaminados
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setIndpisoslaminados(String indpisoslaminados) {
        this.indpisoslaminados = indpisoslaminados == null ? null : indpisoslaminados.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.fechaRegistro
     *
     * @return the value of propiedad.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.fechaRegistro
     *
     * @param fecharegistro the value for propiedad.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.fechaAlta
     *
     * @return the value of propiedad.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Date getFechaalta() {
        return fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.fechaAlta
     *
     * @param fechaalta the value for propiedad.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.fechaBaja
     *
     * @return the value of propiedad.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.fechaBaja
     *
     * @param fechabaja the value for propiedad.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.fechaUltimoEvento
     *
     * @return the value of propiedad.fechaUltimoEvento
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Date getFechaultimoevento() {
        return fechaultimoevento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.fechaUltimoEvento
     *
     * @param fechaultimoevento the value for propiedad.fechaUltimoEvento
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setFechaultimoevento(Date fechaultimoevento) {
        this.fechaultimoevento = fechaultimoevento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.usuarioCrea
     *
     * @return the value of propiedad.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.usuarioCrea
     *
     * @param usuariocrea the value for propiedad.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.usuarioModifica
     *
     * @return the value of propiedad.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.usuarioModifica
     *
     * @param usuariomodifica the value for propiedad.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.fechaCrea
     *
     * @return the value of propiedad.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.fechaCrea
     *
     * @param fechacrea the value for propiedad.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.fechaModifica
     *
     * @return the value of propiedad.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.fechaModifica
     *
     * @param fechamodifica the value for propiedad.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codFranquicia
     *
     * @return the value of propiedad.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Integer getCodfranquicia() {
        return codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codFranquicia
     *
     * @param codfranquicia the value for propiedad.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodfranquicia(Integer codfranquicia) {
        this.codfranquicia = codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedad.codUsuarioAsesor
     *
     * @return the value of propiedad.codUsuarioAsesor
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public Long getCodusuarioasesor() {
        return codusuarioasesor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedad.codUsuarioAsesor
     *
     * @param codusuarioasesor the value for propiedad.codUsuarioAsesor
     *
     * @ibatorgenerated Mon Dec 18 02:04:45 GMT 2017
     */
    public void setCodusuarioasesor(Long codusuarioasesor) {
        this.codusuarioasesor = codusuarioasesor;
    }
}