package pe.bhintranet.model.bean;

import java.util.Date;

public class PropiedadPropietario {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.codPropiedadPropietario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Long codpropiedadpropietario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.codPropiedad
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Long codpropiedad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.dni
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String dni;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.nombres
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombres;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.apellidos
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String apellidos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.sexo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String sexo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.correo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String correo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.telefono
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String telefono;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.celular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String celular;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.celularSecundario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String celularsecundario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.direccion
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String direccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.nombreArchivoFoto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrearchivofoto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.indTitular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String indtitular;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.comentario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String comentario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codfranquicia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.celularWsap
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String celularwsap;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadpropietario.cuentaFacebook
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String cuentafacebook;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.codPropiedadPropietario
     *
     * @return the value of propiedadpropietario.codPropiedadPropietario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Long getCodpropiedadpropietario() {
        return codpropiedadpropietario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.codPropiedadPropietario
     *
     * @param codpropiedadpropietario the value for propiedadpropietario.codPropiedadPropietario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodpropiedadpropietario(Long codpropiedadpropietario) {
        this.codpropiedadpropietario = codpropiedadpropietario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.codPropiedad
     *
     * @return the value of propiedadpropietario.codPropiedad
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Long getCodpropiedad() {
        return codpropiedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.codPropiedad
     *
     * @param codpropiedad the value for propiedadpropietario.codPropiedad
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodpropiedad(Long codpropiedad) {
        this.codpropiedad = codpropiedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.dni
     *
     * @return the value of propiedadpropietario.dni
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getDni() {
        return dni;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.dni
     *
     * @param dni the value for propiedadpropietario.dni
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setDni(String dni) {
        this.dni = dni == null ? null : dni.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.nombres
     *
     * @return the value of propiedadpropietario.nombres
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.nombres
     *
     * @param nombres the value for propiedadpropietario.nombres
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombres(String nombres) {
        this.nombres = nombres == null ? null : nombres.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.apellidos
     *
     * @return the value of propiedadpropietario.apellidos
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getApellidos() {
        return apellidos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.apellidos
     *
     * @param apellidos the value for propiedadpropietario.apellidos
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos == null ? null : apellidos.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.sexo
     *
     * @return the value of propiedadpropietario.sexo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getSexo() {
        return sexo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.sexo
     *
     * @param sexo the value for propiedadpropietario.sexo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setSexo(String sexo) {
        this.sexo = sexo == null ? null : sexo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.correo
     *
     * @return the value of propiedadpropietario.correo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.correo
     *
     * @param correo the value for propiedadpropietario.correo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCorreo(String correo) {
        this.correo = correo == null ? null : correo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.telefono
     *
     * @return the value of propiedadpropietario.telefono
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.telefono
     *
     * @param telefono the value for propiedadpropietario.telefono
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono == null ? null : telefono.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.celular
     *
     * @return the value of propiedadpropietario.celular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCelular() {
        return celular;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.celular
     *
     * @param celular the value for propiedadpropietario.celular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCelular(String celular) {
        this.celular = celular == null ? null : celular.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.celularSecundario
     *
     * @return the value of propiedadpropietario.celularSecundario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCelularsecundario() {
        return celularsecundario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.celularSecundario
     *
     * @param celularsecundario the value for propiedadpropietario.celularSecundario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCelularsecundario(String celularsecundario) {
        this.celularsecundario = celularsecundario == null ? null : celularsecundario.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.direccion
     *
     * @return the value of propiedadpropietario.direccion
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.direccion
     *
     * @param direccion the value for propiedadpropietario.direccion
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion == null ? null : direccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.nombreArchivoFoto
     *
     * @return the value of propiedadpropietario.nombreArchivoFoto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrearchivofoto() {
        return nombrearchivofoto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.nombreArchivoFoto
     *
     * @param nombrearchivofoto the value for propiedadpropietario.nombreArchivoFoto
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrearchivofoto(String nombrearchivofoto) {
        this.nombrearchivofoto = nombrearchivofoto == null ? null : nombrearchivofoto.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.indTitular
     *
     * @return the value of propiedadpropietario.indTitular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getIndtitular() {
        return indtitular;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.indTitular
     *
     * @param indtitular the value for propiedadpropietario.indTitular
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setIndtitular(String indtitular) {
        this.indtitular = indtitular == null ? null : indtitular.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.comentario
     *
     * @return the value of propiedadpropietario.comentario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getComentario() {
        return comentario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.comentario
     *
     * @param comentario the value for propiedadpropietario.comentario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setComentario(String comentario) {
        this.comentario = comentario == null ? null : comentario.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.fechaRegistro
     *
     * @return the value of propiedadpropietario.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.fechaRegistro
     *
     * @param fecharegistro the value for propiedadpropietario.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.estado
     *
     * @return the value of propiedadpropietario.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.estado
     *
     * @param estado the value for propiedadpropietario.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.codFranquicia
     *
     * @return the value of propiedadpropietario.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodfranquicia() {
        return codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.codFranquicia
     *
     * @param codfranquicia the value for propiedadpropietario.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodfranquicia(Integer codfranquicia) {
        this.codfranquicia = codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.usuarioCrea
     *
     * @return the value of propiedadpropietario.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.usuarioCrea
     *
     * @param usuariocrea the value for propiedadpropietario.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.usuarioModifica
     *
     * @return the value of propiedadpropietario.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.usuarioModifica
     *
     * @param usuariomodifica the value for propiedadpropietario.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.fechaCrea
     *
     * @return the value of propiedadpropietario.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.fechaCrea
     *
     * @param fechacrea the value for propiedadpropietario.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.fechaModifica
     *
     * @return the value of propiedadpropietario.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.fechaModifica
     *
     * @param fechamodifica the value for propiedadpropietario.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.celularWsap
     *
     * @return the value of propiedadpropietario.celularWsap
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCelularwsap() {
        return celularwsap;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.celularWsap
     *
     * @param celularwsap the value for propiedadpropietario.celularWsap
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCelularwsap(String celularwsap) {
        this.celularwsap = celularwsap == null ? null : celularwsap.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadpropietario.cuentaFacebook
     *
     * @return the value of propiedadpropietario.cuentaFacebook
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCuentafacebook() {
        return cuentafacebook;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadpropietario.cuentaFacebook
     *
     * @param cuentafacebook the value for propiedadpropietario.cuentaFacebook
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCuentafacebook(String cuentafacebook) {
        this.cuentafacebook = cuentafacebook == null ? null : cuentafacebook.trim();
    }
}