package pe.bhintranet.model.bean;

import java.util.Date;

public class PropiedadArchivo {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.codPropiedadArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Long codpropiedadarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.codPropiedad
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Long codpropiedad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.nombreArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String nombrearchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.descripcionArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String descripcionarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.codExtensionArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String codextensionarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.rutaArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String rutaarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.archivoBinario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String archivobinario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.codTipoArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String codtipoarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.codGrupoArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String codgrupoarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.ordenItem
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer ordenitem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechaalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechabaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column propiedadarchivo.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codfranquicia;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.codPropiedadArchivo
     *
     * @return the value of propiedadarchivo.codPropiedadArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Long getCodpropiedadarchivo() {
        return codpropiedadarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.codPropiedadArchivo
     *
     * @param codpropiedadarchivo the value for propiedadarchivo.codPropiedadArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodpropiedadarchivo(Long codpropiedadarchivo) {
        this.codpropiedadarchivo = codpropiedadarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.codPropiedad
     *
     * @return the value of propiedadarchivo.codPropiedad
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Long getCodpropiedad() {
        return codpropiedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.codPropiedad
     *
     * @param codpropiedad the value for propiedadarchivo.codPropiedad
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodpropiedad(Long codpropiedad) {
        this.codpropiedad = codpropiedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.nombreArchivo
     *
     * @return the value of propiedadarchivo.nombreArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getNombrearchivo() {
        return nombrearchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.nombreArchivo
     *
     * @param nombrearchivo the value for propiedadarchivo.nombreArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setNombrearchivo(String nombrearchivo) {
        this.nombrearchivo = nombrearchivo == null ? null : nombrearchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.descripcionArchivo
     *
     * @return the value of propiedadarchivo.descripcionArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getDescripcionarchivo() {
        return descripcionarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.descripcionArchivo
     *
     * @param descripcionarchivo the value for propiedadarchivo.descripcionArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setDescripcionarchivo(String descripcionarchivo) {
        this.descripcionarchivo = descripcionarchivo == null ? null : descripcionarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.codExtensionArchivo
     *
     * @return the value of propiedadarchivo.codExtensionArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCodextensionarchivo() {
        return codextensionarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.codExtensionArchivo
     *
     * @param codextensionarchivo the value for propiedadarchivo.codExtensionArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodextensionarchivo(String codextensionarchivo) {
        this.codextensionarchivo = codextensionarchivo == null ? null : codextensionarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.rutaArchivo
     *
     * @return the value of propiedadarchivo.rutaArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getRutaarchivo() {
        return rutaarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.rutaArchivo
     *
     * @param rutaarchivo the value for propiedadarchivo.rutaArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setRutaarchivo(String rutaarchivo) {
        this.rutaarchivo = rutaarchivo == null ? null : rutaarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.archivoBinario
     *
     * @return the value of propiedadarchivo.archivoBinario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getArchivobinario() {
        return archivobinario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.archivoBinario
     *
     * @param archivobinario the value for propiedadarchivo.archivoBinario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setArchivobinario(String archivobinario) {
        this.archivobinario = archivobinario == null ? null : archivobinario.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.codTipoArchivo
     *
     * @return the value of propiedadarchivo.codTipoArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCodtipoarchivo() {
        return codtipoarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.codTipoArchivo
     *
     * @param codtipoarchivo the value for propiedadarchivo.codTipoArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodtipoarchivo(String codtipoarchivo) {
        this.codtipoarchivo = codtipoarchivo == null ? null : codtipoarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.codGrupoArchivo
     *
     * @return the value of propiedadarchivo.codGrupoArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getCodgrupoarchivo() {
        return codgrupoarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.codGrupoArchivo
     *
     * @param codgrupoarchivo the value for propiedadarchivo.codGrupoArchivo
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodgrupoarchivo(String codgrupoarchivo) {
        this.codgrupoarchivo = codgrupoarchivo == null ? null : codgrupoarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.ordenItem
     *
     * @return the value of propiedadarchivo.ordenItem
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getOrdenitem() {
        return ordenitem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.ordenItem
     *
     * @param ordenitem the value for propiedadarchivo.ordenItem
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setOrdenitem(Integer ordenitem) {
        this.ordenitem = ordenitem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.fechaRegistro
     *
     * @return the value of propiedadarchivo.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.fechaRegistro
     *
     * @param fecharegistro the value for propiedadarchivo.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.fechaAlta
     *
     * @return the value of propiedadarchivo.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechaalta() {
        return fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.fechaAlta
     *
     * @param fechaalta the value for propiedadarchivo.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.fechaBaja
     *
     * @return the value of propiedadarchivo.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.fechaBaja
     *
     * @param fechabaja the value for propiedadarchivo.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.estado
     *
     * @return the value of propiedadarchivo.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.estado
     *
     * @param estado the value for propiedadarchivo.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.usuarioCrea
     *
     * @return the value of propiedadarchivo.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.usuarioCrea
     *
     * @param usuariocrea the value for propiedadarchivo.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.usuarioModifica
     *
     * @return the value of propiedadarchivo.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.usuarioModifica
     *
     * @param usuariomodifica the value for propiedadarchivo.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.fechaCrea
     *
     * @return the value of propiedadarchivo.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.fechaCrea
     *
     * @param fechacrea the value for propiedadarchivo.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.fechaModifica
     *
     * @return the value of propiedadarchivo.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.fechaModifica
     *
     * @param fechamodifica the value for propiedadarchivo.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column propiedadarchivo.codFranquicia
     *
     * @return the value of propiedadarchivo.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodfranquicia() {
        return codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column propiedadarchivo.codFranquicia
     *
     * @param codfranquicia the value for propiedadarchivo.codFranquicia
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodfranquicia(Integer codfranquicia) {
        this.codfranquicia = codfranquicia;
    }
}