package pe.bhintranet.model.bean;

import java.util.Date;

public class TasacionArchivo {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.codTasacionArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codtasacionarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codtasacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.codGrupoArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String codgrupoarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.codTipoArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String codtipoarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.nombreArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String nombrearchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.descripcionArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String descripcionarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.rutaArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String rutaarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.codExtensionArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String codextensionarchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechaalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechabaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionarchivo.codFranquicia
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Integer codfranquicia;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.codTasacionArchivo
     *
     * @return the value of tasacionarchivo.codTasacionArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodtasacionarchivo() {
        return codtasacionarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.codTasacionArchivo
     *
     * @param codtasacionarchivo the value for tasacionarchivo.codTasacionArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodtasacionarchivo(Long codtasacionarchivo) {
        this.codtasacionarchivo = codtasacionarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.codTasacion
     *
     * @return the value of tasacionarchivo.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodtasacion() {
        return codtasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.codTasacion
     *
     * @param codtasacion the value for tasacionarchivo.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodtasacion(Long codtasacion) {
        this.codtasacion = codtasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.codGrupoArchivo
     *
     * @return the value of tasacionarchivo.codGrupoArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getCodgrupoarchivo() {
        return codgrupoarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.codGrupoArchivo
     *
     * @param codgrupoarchivo the value for tasacionarchivo.codGrupoArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodgrupoarchivo(String codgrupoarchivo) {
        this.codgrupoarchivo = codgrupoarchivo == null ? null : codgrupoarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.codTipoArchivo
     *
     * @return the value of tasacionarchivo.codTipoArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getCodtipoarchivo() {
        return codtipoarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.codTipoArchivo
     *
     * @param codtipoarchivo the value for tasacionarchivo.codTipoArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodtipoarchivo(String codtipoarchivo) {
        this.codtipoarchivo = codtipoarchivo == null ? null : codtipoarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.nombreArchivo
     *
     * @return the value of tasacionarchivo.nombreArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getNombrearchivo() {
        return nombrearchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.nombreArchivo
     *
     * @param nombrearchivo the value for tasacionarchivo.nombreArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setNombrearchivo(String nombrearchivo) {
        this.nombrearchivo = nombrearchivo == null ? null : nombrearchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.descripcionArchivo
     *
     * @return the value of tasacionarchivo.descripcionArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDescripcionarchivo() {
        return descripcionarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.descripcionArchivo
     *
     * @param descripcionarchivo the value for tasacionarchivo.descripcionArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDescripcionarchivo(String descripcionarchivo) {
        this.descripcionarchivo = descripcionarchivo == null ? null : descripcionarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.rutaArchivo
     *
     * @return the value of tasacionarchivo.rutaArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getRutaarchivo() {
        return rutaarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.rutaArchivo
     *
     * @param rutaarchivo the value for tasacionarchivo.rutaArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setRutaarchivo(String rutaarchivo) {
        this.rutaarchivo = rutaarchivo == null ? null : rutaarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.codExtensionArchivo
     *
     * @return the value of tasacionarchivo.codExtensionArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getCodextensionarchivo() {
        return codextensionarchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.codExtensionArchivo
     *
     * @param codextensionarchivo the value for tasacionarchivo.codExtensionArchivo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodextensionarchivo(String codextensionarchivo) {
        this.codextensionarchivo = codextensionarchivo == null ? null : codextensionarchivo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.fechaRegistro
     *
     * @return the value of tasacionarchivo.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.fechaRegistro
     *
     * @param fecharegistro the value for tasacionarchivo.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.fechaAlta
     *
     * @return the value of tasacionarchivo.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechaalta() {
        return fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.fechaAlta
     *
     * @param fechaalta the value for tasacionarchivo.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.fechaBaja
     *
     * @return the value of tasacionarchivo.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.fechaBaja
     *
     * @param fechabaja the value for tasacionarchivo.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.estado
     *
     * @return the value of tasacionarchivo.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.estado
     *
     * @param estado the value for tasacionarchivo.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.usuarioCrea
     *
     * @return the value of tasacionarchivo.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.usuarioCrea
     *
     * @param usuariocrea the value for tasacionarchivo.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.usuarioModifica
     *
     * @return the value of tasacionarchivo.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.usuarioModifica
     *
     * @param usuariomodifica the value for tasacionarchivo.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.fechaCrea
     *
     * @return the value of tasacionarchivo.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.fechaCrea
     *
     * @param fechacrea the value for tasacionarchivo.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.fechaModifica
     *
     * @return the value of tasacionarchivo.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.fechaModifica
     *
     * @param fechamodifica the value for tasacionarchivo.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionarchivo.codFranquicia
     *
     * @return the value of tasacionarchivo.codFranquicia
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Integer getCodfranquicia() {
        return codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionarchivo.codFranquicia
     *
     * @param codfranquicia the value for tasacionarchivo.codFranquicia
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodfranquicia(Integer codfranquicia) {
        this.codfranquicia = codfranquicia;
    }
}