package pe.bhintranet.model.bean;

import java.math.BigDecimal;
import java.util.Date;

public class TasacionEdificacion {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codtasacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.nroItem
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Integer nroitem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.concepto
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String concepto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.areaM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal aream2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.valorM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal valorm2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.factorDepreciacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal factordepreciacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.valorTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal valortotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionedificacion.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.codTasacion
     *
     * @return the value of tasacionedificacion.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodtasacion() {
        return codtasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.codTasacion
     *
     * @param codtasacion the value for tasacionedificacion.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodtasacion(Long codtasacion) {
        this.codtasacion = codtasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.nroItem
     *
     * @return the value of tasacionedificacion.nroItem
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Integer getNroitem() {
        return nroitem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.nroItem
     *
     * @param nroitem the value for tasacionedificacion.nroItem
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setNroitem(Integer nroitem) {
        this.nroitem = nroitem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.concepto
     *
     * @return the value of tasacionedificacion.concepto
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getConcepto() {
        return concepto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.concepto
     *
     * @param concepto the value for tasacionedificacion.concepto
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setConcepto(String concepto) {
        this.concepto = concepto == null ? null : concepto.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.areaM2
     *
     * @return the value of tasacionedificacion.areaM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getAream2() {
        return aream2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.areaM2
     *
     * @param aream2 the value for tasacionedificacion.areaM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setAream2(BigDecimal aream2) {
        this.aream2 = aream2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.valorM2
     *
     * @return the value of tasacionedificacion.valorM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getValorm2() {
        return valorm2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.valorM2
     *
     * @param valorm2 the value for tasacionedificacion.valorM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setValorm2(BigDecimal valorm2) {
        this.valorm2 = valorm2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.factorDepreciacion
     *
     * @return the value of tasacionedificacion.factorDepreciacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getFactordepreciacion() {
        return factordepreciacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.factorDepreciacion
     *
     * @param factordepreciacion the value for tasacionedificacion.factorDepreciacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFactordepreciacion(BigDecimal factordepreciacion) {
        this.factordepreciacion = factordepreciacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.valorTotal
     *
     * @return the value of tasacionedificacion.valorTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getValortotal() {
        return valortotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.valorTotal
     *
     * @param valortotal the value for tasacionedificacion.valorTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setValortotal(BigDecimal valortotal) {
        this.valortotal = valortotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.fechaRegistro
     *
     * @return the value of tasacionedificacion.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.fechaRegistro
     *
     * @param fecharegistro the value for tasacionedificacion.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.estado
     *
     * @return the value of tasacionedificacion.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.estado
     *
     * @param estado the value for tasacionedificacion.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.usuarioCrea
     *
     * @return the value of tasacionedificacion.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.usuarioCrea
     *
     * @param usuariocrea the value for tasacionedificacion.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.usuarioModifica
     *
     * @return the value of tasacionedificacion.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.usuarioModifica
     *
     * @param usuariomodifica the value for tasacionedificacion.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.fechaCrea
     *
     * @return the value of tasacionedificacion.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.fechaCrea
     *
     * @param fechacrea the value for tasacionedificacion.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionedificacion.fechaModifica
     *
     * @return the value of tasacionedificacion.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionedificacion.fechaModifica
     *
     * @param fechamodifica the value for tasacionedificacion.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }
}