package pe.bhintranet.model.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Tasacion {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codtasacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.codPropiedad
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codpropiedad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.codTipoBien
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String codtipobien;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.telefono
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String telefono;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.fechaTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechatasacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.tipoCambio
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal tipocambio;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.finalidad
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String finalidad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.instruccionesRecibidas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String instruccionesrecibidas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.detalleLaborRealizada
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String detallelaborrealizada;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.datosUbicacionGmap
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String datosubicaciongmap;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.datosDescripcion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String datosdescripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.datosUsoActual
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String datosusoactual;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.numeroPartidaRegistral
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String numeropartidaregistral;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.infraestructuraServiciosUrba
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String infraestructuraserviciosurba;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.terrenoValorM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal terrenovalorm2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.terrenoCantidadM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal terrenocantidadm2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.terrenoValorTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal terrenovalortotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.estadoConservacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String estadoconservacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.valorDepreciacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal valordepreciacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.edificacionValorTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal edificacionvalortotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.valorTasacionDirecta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal valortasaciondirecta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.valorComercialTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal valorcomercialtotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.valorRealizacionTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal valorrealizaciontotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.monedaServicio
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String monedaservicio;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.costoServicio
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private BigDecimal costoservicio;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.correo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String correo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.nombresCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String nombrescliente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.apellidosCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String apellidoscliente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.dniCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String dnicliente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.rucCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String ruccliente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.razonSocialCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String razonsocialcliente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.tipoPersona
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String tipopersona;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.codCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codcliente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.codEmpresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codempresa;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.codPersonaTasador
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codpersonatasador;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.numeroInforme
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String numeroinforme;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.periodo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String periodo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.cimientos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String cimientos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.columnas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String columnas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.muros
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String muros;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.techos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String techos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.pisos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String pisos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.puertas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String puertas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.ventanas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String ventanas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.revestimiento
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String revestimiento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.banos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String banos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.electricas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String electricas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.sanitarios
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String sanitarios;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechaalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechabaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.codFranquicia
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Integer codfranquicia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacion.codUsuarioTasador
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codusuariotasador;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.codTasacion
     *
     * @return the value of tasacion.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodtasacion() {
        return codtasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.codTasacion
     *
     * @param codtasacion the value for tasacion.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodtasacion(Long codtasacion) {
        this.codtasacion = codtasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.codPropiedad
     *
     * @return the value of tasacion.codPropiedad
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodpropiedad() {
        return codpropiedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.codPropiedad
     *
     * @param codpropiedad the value for tasacion.codPropiedad
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodpropiedad(Long codpropiedad) {
        this.codpropiedad = codpropiedad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.codTipoBien
     *
     * @return the value of tasacion.codTipoBien
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getCodtipobien() {
        return codtipobien;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.codTipoBien
     *
     * @param codtipobien the value for tasacion.codTipoBien
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodtipobien(String codtipobien) {
        this.codtipobien = codtipobien == null ? null : codtipobien.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.telefono
     *
     * @return the value of tasacion.telefono
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.telefono
     *
     * @param telefono the value for tasacion.telefono
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono == null ? null : telefono.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.fechaTasacion
     *
     * @return the value of tasacion.fechaTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechatasacion() {
        return fechatasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.fechaTasacion
     *
     * @param fechatasacion the value for tasacion.fechaTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechatasacion(Date fechatasacion) {
        this.fechatasacion = fechatasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.tipoCambio
     *
     * @return the value of tasacion.tipoCambio
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getTipocambio() {
        return tipocambio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.tipoCambio
     *
     * @param tipocambio the value for tasacion.tipoCambio
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setTipocambio(BigDecimal tipocambio) {
        this.tipocambio = tipocambio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.finalidad
     *
     * @return the value of tasacion.finalidad
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getFinalidad() {
        return finalidad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.finalidad
     *
     * @param finalidad the value for tasacion.finalidad
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFinalidad(String finalidad) {
        this.finalidad = finalidad == null ? null : finalidad.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.instruccionesRecibidas
     *
     * @return the value of tasacion.instruccionesRecibidas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getInstruccionesrecibidas() {
        return instruccionesrecibidas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.instruccionesRecibidas
     *
     * @param instruccionesrecibidas the value for tasacion.instruccionesRecibidas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setInstruccionesrecibidas(String instruccionesrecibidas) {
        this.instruccionesrecibidas = instruccionesrecibidas == null ? null : instruccionesrecibidas.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.detalleLaborRealizada
     *
     * @return the value of tasacion.detalleLaborRealizada
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDetallelaborrealizada() {
        return detallelaborrealizada;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.detalleLaborRealizada
     *
     * @param detallelaborrealizada the value for tasacion.detalleLaborRealizada
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDetallelaborrealizada(String detallelaborrealizada) {
        this.detallelaborrealizada = detallelaborrealizada == null ? null : detallelaborrealizada.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.datosUbicacionGmap
     *
     * @return the value of tasacion.datosUbicacionGmap
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDatosubicaciongmap() {
        return datosubicaciongmap;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.datosUbicacionGmap
     *
     * @param datosubicaciongmap the value for tasacion.datosUbicacionGmap
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDatosubicaciongmap(String datosubicaciongmap) {
        this.datosubicaciongmap = datosubicaciongmap == null ? null : datosubicaciongmap.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.datosDescripcion
     *
     * @return the value of tasacion.datosDescripcion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDatosdescripcion() {
        return datosdescripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.datosDescripcion
     *
     * @param datosdescripcion the value for tasacion.datosDescripcion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDatosdescripcion(String datosdescripcion) {
        this.datosdescripcion = datosdescripcion == null ? null : datosdescripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.datosUsoActual
     *
     * @return the value of tasacion.datosUsoActual
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDatosusoactual() {
        return datosusoactual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.datosUsoActual
     *
     * @param datosusoactual the value for tasacion.datosUsoActual
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDatosusoactual(String datosusoactual) {
        this.datosusoactual = datosusoactual == null ? null : datosusoactual.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.numeroPartidaRegistral
     *
     * @return the value of tasacion.numeroPartidaRegistral
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getNumeropartidaregistral() {
        return numeropartidaregistral;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.numeroPartidaRegistral
     *
     * @param numeropartidaregistral the value for tasacion.numeroPartidaRegistral
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setNumeropartidaregistral(String numeropartidaregistral) {
        this.numeropartidaregistral = numeropartidaregistral == null ? null : numeropartidaregistral.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.infraestructuraServiciosUrba
     *
     * @return the value of tasacion.infraestructuraServiciosUrba
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getInfraestructuraserviciosurba() {
        return infraestructuraserviciosurba;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.infraestructuraServiciosUrba
     *
     * @param infraestructuraserviciosurba the value for tasacion.infraestructuraServiciosUrba
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setInfraestructuraserviciosurba(String infraestructuraserviciosurba) {
        this.infraestructuraserviciosurba = infraestructuraserviciosurba == null ? null : infraestructuraserviciosurba.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.terrenoValorM2
     *
     * @return the value of tasacion.terrenoValorM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getTerrenovalorm2() {
        return terrenovalorm2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.terrenoValorM2
     *
     * @param terrenovalorm2 the value for tasacion.terrenoValorM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setTerrenovalorm2(BigDecimal terrenovalorm2) {
        this.terrenovalorm2 = terrenovalorm2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.terrenoCantidadM2
     *
     * @return the value of tasacion.terrenoCantidadM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getTerrenocantidadm2() {
        return terrenocantidadm2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.terrenoCantidadM2
     *
     * @param terrenocantidadm2 the value for tasacion.terrenoCantidadM2
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setTerrenocantidadm2(BigDecimal terrenocantidadm2) {
        this.terrenocantidadm2 = terrenocantidadm2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.terrenoValorTotal
     *
     * @return the value of tasacion.terrenoValorTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getTerrenovalortotal() {
        return terrenovalortotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.terrenoValorTotal
     *
     * @param terrenovalortotal the value for tasacion.terrenoValorTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setTerrenovalortotal(BigDecimal terrenovalortotal) {
        this.terrenovalortotal = terrenovalortotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.estadoConservacion
     *
     * @return the value of tasacion.estadoConservacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getEstadoconservacion() {
        return estadoconservacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.estadoConservacion
     *
     * @param estadoconservacion the value for tasacion.estadoConservacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setEstadoconservacion(String estadoconservacion) {
        this.estadoconservacion = estadoconservacion == null ? null : estadoconservacion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.valorDepreciacion
     *
     * @return the value of tasacion.valorDepreciacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getValordepreciacion() {
        return valordepreciacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.valorDepreciacion
     *
     * @param valordepreciacion the value for tasacion.valorDepreciacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setValordepreciacion(BigDecimal valordepreciacion) {
        this.valordepreciacion = valordepreciacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.edificacionValorTotal
     *
     * @return the value of tasacion.edificacionValorTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getEdificacionvalortotal() {
        return edificacionvalortotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.edificacionValorTotal
     *
     * @param edificacionvalortotal the value for tasacion.edificacionValorTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setEdificacionvalortotal(BigDecimal edificacionvalortotal) {
        this.edificacionvalortotal = edificacionvalortotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.valorTasacionDirecta
     *
     * @return the value of tasacion.valorTasacionDirecta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getValortasaciondirecta() {
        return valortasaciondirecta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.valorTasacionDirecta
     *
     * @param valortasaciondirecta the value for tasacion.valorTasacionDirecta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setValortasaciondirecta(BigDecimal valortasaciondirecta) {
        this.valortasaciondirecta = valortasaciondirecta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.valorComercialTotal
     *
     * @return the value of tasacion.valorComercialTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getValorcomercialtotal() {
        return valorcomercialtotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.valorComercialTotal
     *
     * @param valorcomercialtotal the value for tasacion.valorComercialTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setValorcomercialtotal(BigDecimal valorcomercialtotal) {
        this.valorcomercialtotal = valorcomercialtotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.valorRealizacionTotal
     *
     * @return the value of tasacion.valorRealizacionTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getValorrealizaciontotal() {
        return valorrealizaciontotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.valorRealizacionTotal
     *
     * @param valorrealizaciontotal the value for tasacion.valorRealizacionTotal
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setValorrealizaciontotal(BigDecimal valorrealizaciontotal) {
        this.valorrealizaciontotal = valorrealizaciontotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.monedaServicio
     *
     * @return the value of tasacion.monedaServicio
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getMonedaservicio() {
        return monedaservicio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.monedaServicio
     *
     * @param monedaservicio the value for tasacion.monedaServicio
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setMonedaservicio(String monedaservicio) {
        this.monedaservicio = monedaservicio == null ? null : monedaservicio.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.costoServicio
     *
     * @return the value of tasacion.costoServicio
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public BigDecimal getCostoservicio() {
        return costoservicio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.costoServicio
     *
     * @param costoservicio the value for tasacion.costoServicio
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCostoservicio(BigDecimal costoservicio) {
        this.costoservicio = costoservicio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.correo
     *
     * @return the value of tasacion.correo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.correo
     *
     * @param correo the value for tasacion.correo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCorreo(String correo) {
        this.correo = correo == null ? null : correo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.nombresCliente
     *
     * @return the value of tasacion.nombresCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getNombrescliente() {
        return nombrescliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.nombresCliente
     *
     * @param nombrescliente the value for tasacion.nombresCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setNombrescliente(String nombrescliente) {
        this.nombrescliente = nombrescliente == null ? null : nombrescliente.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.apellidosCliente
     *
     * @return the value of tasacion.apellidosCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getApellidoscliente() {
        return apellidoscliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.apellidosCliente
     *
     * @param apellidoscliente the value for tasacion.apellidosCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setApellidoscliente(String apellidoscliente) {
        this.apellidoscliente = apellidoscliente == null ? null : apellidoscliente.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.dniCliente
     *
     * @return the value of tasacion.dniCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDnicliente() {
        return dnicliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.dniCliente
     *
     * @param dnicliente the value for tasacion.dniCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDnicliente(String dnicliente) {
        this.dnicliente = dnicliente == null ? null : dnicliente.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.rucCliente
     *
     * @return the value of tasacion.rucCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getRuccliente() {
        return ruccliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.rucCliente
     *
     * @param ruccliente the value for tasacion.rucCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setRuccliente(String ruccliente) {
        this.ruccliente = ruccliente == null ? null : ruccliente.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.razonSocialCliente
     *
     * @return the value of tasacion.razonSocialCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getRazonsocialcliente() {
        return razonsocialcliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.razonSocialCliente
     *
     * @param razonsocialcliente the value for tasacion.razonSocialCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setRazonsocialcliente(String razonsocialcliente) {
        this.razonsocialcliente = razonsocialcliente == null ? null : razonsocialcliente.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.tipoPersona
     *
     * @return the value of tasacion.tipoPersona
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getTipopersona() {
        return tipopersona;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.tipoPersona
     *
     * @param tipopersona the value for tasacion.tipoPersona
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setTipopersona(String tipopersona) {
        this.tipopersona = tipopersona == null ? null : tipopersona.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.codCliente
     *
     * @return the value of tasacion.codCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodcliente() {
        return codcliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.codCliente
     *
     * @param codcliente the value for tasacion.codCliente
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodcliente(Long codcliente) {
        this.codcliente = codcliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.codEmpresa
     *
     * @return the value of tasacion.codEmpresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodempresa() {
        return codempresa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.codEmpresa
     *
     * @param codempresa the value for tasacion.codEmpresa
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodempresa(Long codempresa) {
        this.codempresa = codempresa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.codPersonaTasador
     *
     * @return the value of tasacion.codPersonaTasador
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodpersonatasador() {
        return codpersonatasador;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.codPersonaTasador
     *
     * @param codpersonatasador the value for tasacion.codPersonaTasador
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodpersonatasador(Long codpersonatasador) {
        this.codpersonatasador = codpersonatasador;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.numeroInforme
     *
     * @return the value of tasacion.numeroInforme
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getNumeroinforme() {
        return numeroinforme;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.numeroInforme
     *
     * @param numeroinforme the value for tasacion.numeroInforme
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setNumeroinforme(String numeroinforme) {
        this.numeroinforme = numeroinforme == null ? null : numeroinforme.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.periodo
     *
     * @return the value of tasacion.periodo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getPeriodo() {
        return periodo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.periodo
     *
     * @param periodo the value for tasacion.periodo
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setPeriodo(String periodo) {
        this.periodo = periodo == null ? null : periodo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.cimientos
     *
     * @return the value of tasacion.cimientos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getCimientos() {
        return cimientos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.cimientos
     *
     * @param cimientos the value for tasacion.cimientos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCimientos(String cimientos) {
        this.cimientos = cimientos == null ? null : cimientos.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.columnas
     *
     * @return the value of tasacion.columnas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getColumnas() {
        return columnas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.columnas
     *
     * @param columnas the value for tasacion.columnas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setColumnas(String columnas) {
        this.columnas = columnas == null ? null : columnas.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.muros
     *
     * @return the value of tasacion.muros
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getMuros() {
        return muros;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.muros
     *
     * @param muros the value for tasacion.muros
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setMuros(String muros) {
        this.muros = muros == null ? null : muros.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.techos
     *
     * @return the value of tasacion.techos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getTechos() {
        return techos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.techos
     *
     * @param techos the value for tasacion.techos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setTechos(String techos) {
        this.techos = techos == null ? null : techos.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.pisos
     *
     * @return the value of tasacion.pisos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getPisos() {
        return pisos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.pisos
     *
     * @param pisos the value for tasacion.pisos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setPisos(String pisos) {
        this.pisos = pisos == null ? null : pisos.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.puertas
     *
     * @return the value of tasacion.puertas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getPuertas() {
        return puertas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.puertas
     *
     * @param puertas the value for tasacion.puertas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setPuertas(String puertas) {
        this.puertas = puertas == null ? null : puertas.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.ventanas
     *
     * @return the value of tasacion.ventanas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getVentanas() {
        return ventanas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.ventanas
     *
     * @param ventanas the value for tasacion.ventanas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setVentanas(String ventanas) {
        this.ventanas = ventanas == null ? null : ventanas.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.revestimiento
     *
     * @return the value of tasacion.revestimiento
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getRevestimiento() {
        return revestimiento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.revestimiento
     *
     * @param revestimiento the value for tasacion.revestimiento
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setRevestimiento(String revestimiento) {
        this.revestimiento = revestimiento == null ? null : revestimiento.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.banos
     *
     * @return the value of tasacion.banos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getBanos() {
        return banos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.banos
     *
     * @param banos the value for tasacion.banos
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setBanos(String banos) {
        this.banos = banos == null ? null : banos.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.electricas
     *
     * @return the value of tasacion.electricas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getElectricas() {
        return electricas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.electricas
     *
     * @param electricas the value for tasacion.electricas
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setElectricas(String electricas) {
        this.electricas = electricas == null ? null : electricas.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.sanitarios
     *
     * @return the value of tasacion.sanitarios
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getSanitarios() {
        return sanitarios;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.sanitarios
     *
     * @param sanitarios the value for tasacion.sanitarios
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setSanitarios(String sanitarios) {
        this.sanitarios = sanitarios == null ? null : sanitarios.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.fechaRegistro
     *
     * @return the value of tasacion.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.fechaRegistro
     *
     * @param fecharegistro the value for tasacion.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.fechaAlta
     *
     * @return the value of tasacion.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechaalta() {
        return fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.fechaAlta
     *
     * @param fechaalta the value for tasacion.fechaAlta
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.fechaBaja
     *
     * @return the value of tasacion.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.fechaBaja
     *
     * @param fechabaja the value for tasacion.fechaBaja
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.estado
     *
     * @return the value of tasacion.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.estado
     *
     * @param estado the value for tasacion.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.usuarioCrea
     *
     * @return the value of tasacion.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.usuarioCrea
     *
     * @param usuariocrea the value for tasacion.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.usuarioModifica
     *
     * @return the value of tasacion.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.usuarioModifica
     *
     * @param usuariomodifica the value for tasacion.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.fechaCrea
     *
     * @return the value of tasacion.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.fechaCrea
     *
     * @param fechacrea the value for tasacion.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.fechaModifica
     *
     * @return the value of tasacion.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.fechaModifica
     *
     * @param fechamodifica the value for tasacion.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.codFranquicia
     *
     * @return the value of tasacion.codFranquicia
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Integer getCodfranquicia() {
        return codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.codFranquicia
     *
     * @param codfranquicia the value for tasacion.codFranquicia
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodfranquicia(Integer codfranquicia) {
        this.codfranquicia = codfranquicia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacion.codUsuarioTasador
     *
     * @return the value of tasacion.codUsuarioTasador
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodusuariotasador() {
        return codusuariotasador;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacion.codUsuarioTasador
     *
     * @param codusuariotasador the value for tasacion.codUsuarioTasador
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodusuariotasador(Long codusuariotasador) {
        this.codusuariotasador = codusuariotasador;
    }
}