package pe.bhintranet.model.bean;

import java.util.Date;

public class TasacionLinderos {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Long codtasacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.nroItem
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Integer nroitem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.nombre
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.descripcion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tasacionlinderos.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.codTasacion
     *
     * @return the value of tasacionlinderos.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Long getCodtasacion() {
        return codtasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.codTasacion
     *
     * @param codtasacion the value for tasacionlinderos.codTasacion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setCodtasacion(Long codtasacion) {
        this.codtasacion = codtasacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.nroItem
     *
     * @return the value of tasacionlinderos.nroItem
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Integer getNroitem() {
        return nroitem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.nroItem
     *
     * @param nroitem the value for tasacionlinderos.nroItem
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setNroitem(Integer nroitem) {
        this.nroitem = nroitem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.nombre
     *
     * @return the value of tasacionlinderos.nombre
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.nombre
     *
     * @param nombre the value for tasacionlinderos.nombre
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.descripcion
     *
     * @return the value of tasacionlinderos.descripcion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.descripcion
     *
     * @param descripcion the value for tasacionlinderos.descripcion
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.fechaRegistro
     *
     * @return the value of tasacionlinderos.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.fechaRegistro
     *
     * @param fecharegistro the value for tasacionlinderos.fechaRegistro
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.estado
     *
     * @return the value of tasacionlinderos.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.estado
     *
     * @param estado the value for tasacionlinderos.estado
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.usuarioCrea
     *
     * @return the value of tasacionlinderos.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.usuarioCrea
     *
     * @param usuariocrea the value for tasacionlinderos.usuarioCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.usuarioModifica
     *
     * @return the value of tasacionlinderos.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.usuarioModifica
     *
     * @param usuariomodifica the value for tasacionlinderos.usuarioModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.fechaCrea
     *
     * @return the value of tasacionlinderos.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.fechaCrea
     *
     * @param fechacrea the value for tasacionlinderos.fechaCrea
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tasacionlinderos.fechaModifica
     *
     * @return the value of tasacionlinderos.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tasacionlinderos.fechaModifica
     *
     * @param fechamodifica the value for tasacionlinderos.fechaModifica
     *
     * @ibatorgenerated Fri Dec 22 04:07:26 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }
}