package pe.bhintranet.model.bean;

import java.util.Date;

public class UsuarioPerfil {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.codModuloPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Integer codmoduloperfil;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.codUsuario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Long codusuario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fecharegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechaalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechabaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.documAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String documalta;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.documBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String documbaja;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariocrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private String usuariomodifica;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechacrea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usuarioperfil.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    private Date fechamodifica;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.codModuloPerfil
     *
     * @return the value of usuarioperfil.codModuloPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Integer getCodmoduloperfil() {
        return codmoduloperfil;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.codModuloPerfil
     *
     * @param codmoduloperfil the value for usuarioperfil.codModuloPerfil
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodmoduloperfil(Integer codmoduloperfil) {
        this.codmoduloperfil = codmoduloperfil;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.codUsuario
     *
     * @return the value of usuarioperfil.codUsuario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Long getCodusuario() {
        return codusuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.codUsuario
     *
     * @param codusuario the value for usuarioperfil.codUsuario
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setCodusuario(Long codusuario) {
        this.codusuario = codusuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.fechaRegistro
     *
     * @return the value of usuarioperfil.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFecharegistro() {
        return fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.fechaRegistro
     *
     * @param fecharegistro the value for usuarioperfil.fechaRegistro
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.fechaAlta
     *
     * @return the value of usuarioperfil.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechaalta() {
        return fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.fechaAlta
     *
     * @param fechaalta the value for usuarioperfil.fechaAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.fechaBaja
     *
     * @return the value of usuarioperfil.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechabaja() {
        return fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.fechaBaja
     *
     * @param fechabaja the value for usuarioperfil.fechaBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.documAlta
     *
     * @return the value of usuarioperfil.documAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getDocumalta() {
        return documalta;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.documAlta
     *
     * @param documalta the value for usuarioperfil.documAlta
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setDocumalta(String documalta) {
        this.documalta = documalta == null ? null : documalta.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.documBaja
     *
     * @return the value of usuarioperfil.documBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getDocumbaja() {
        return documbaja;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.documBaja
     *
     * @param documbaja the value for usuarioperfil.documBaja
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setDocumbaja(String documbaja) {
        this.documbaja = documbaja == null ? null : documbaja.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.estado
     *
     * @return the value of usuarioperfil.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.estado
     *
     * @param estado the value for usuarioperfil.estado
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.usuarioCrea
     *
     * @return the value of usuarioperfil.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariocrea() {
        return usuariocrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.usuarioCrea
     *
     * @param usuariocrea the value for usuarioperfil.usuarioCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariocrea(String usuariocrea) {
        this.usuariocrea = usuariocrea == null ? null : usuariocrea.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.usuarioModifica
     *
     * @return the value of usuarioperfil.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public String getUsuariomodifica() {
        return usuariomodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.usuarioModifica
     *
     * @param usuariomodifica the value for usuarioperfil.usuarioModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setUsuariomodifica(String usuariomodifica) {
        this.usuariomodifica = usuariomodifica == null ? null : usuariomodifica.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.fechaCrea
     *
     * @return the value of usuarioperfil.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechacrea() {
        return fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.fechaCrea
     *
     * @param fechacrea the value for usuarioperfil.fechaCrea
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usuarioperfil.fechaModifica
     *
     * @return the value of usuarioperfil.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public Date getFechamodifica() {
        return fechamodifica;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usuarioperfil.fechaModifica
     *
     * @param fechamodifica the value for usuarioperfil.fechaModifica
     *
     * @ibatorgenerated Mon Dec 18 01:51:37 GMT 2017
     */
    public void setFechamodifica(Date fechamodifica) {
        this.fechamodifica = fechamodifica;
    }
}